-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_snn_top_hls_Pipeline_RESET_TRACE_OUTER_RESET_TRACE_INNER is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL18eligibility_traces_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_0_ce1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_0_we1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_1_ce1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_1_we1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_2_ce1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_2_we1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_2_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_3_ce1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_3_we1 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_3_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of snn_top_hls_snn_top_hls_Pipeline_RESET_TRACE_OUTER_RESET_TRACE_INNER is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln370_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln370_fu_244_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln370_reg_364 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal trunc_ln371_fu_260_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln371_reg_369 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_7_reg_374 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln373_fu_282_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln373_1_fu_321_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_74 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln371_fu_329_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_78 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln370_1_fu_252_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_82 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln370_1_fu_214_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZL18eligibility_traces_0_we1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_0_ce1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_0_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZL18eligibility_traces_1_we1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_1_ce1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_1_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZL18eligibility_traces_2_we1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_2_ce1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_2_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZL18eligibility_traces_3_we1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_3_ce1_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_3_address1_local : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln370_fu_226_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln370_fu_230_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln1_fu_264_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_274_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_fu_313_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln370_fu_310_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_78 <= ap_const_lv7_0;
            elsif (((icmp_ln370_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                i_fu_78 <= select_ln370_1_fu_252_p3;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                indvar_flatten_fu_82 <= ap_const_lv10_0;
            elsif (((icmp_ln370_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten_fu_82 <= add_ln370_1_fu_214_p2;
            end if; 
        end if;
    end process;

    j_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_74 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_74 <= add_ln371_fu_329_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                select_ln370_reg_364 <= select_ln370_fu_244_p3;
                tmp_7_reg_374 <= select_ln370_fu_244_p3(5 downto 3);
                trunc_ln371_reg_369 <= trunc_ln371_fu_260_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln370_1_fu_214_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_82) + unsigned(ap_const_lv10_1));
    add_ln370_fu_230_p2 <= std_logic_vector(unsigned(i_fu_78) + unsigned(ap_const_lv7_1));
    add_ln371_fu_329_p2 <= std_logic_vector(unsigned(zext_ln370_fu_310_p1) + unsigned(ap_const_lv7_8));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln370_fu_208_p2)
    begin
        if (((icmp_ln370_fu_208_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln370_fu_208_p2 <= "1" when (indvar_flatten_fu_82 = ap_const_lv10_200) else "0";
    lshr_ln1_fu_264_p4 <= select_ln370_fu_244_p3(5 downto 2);
    p_ZL18eligibility_traces_0_address1 <= p_ZL18eligibility_traces_0_address1_local;

    p_ZL18eligibility_traces_0_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, zext_ln373_fu_282_p1, ap_block_pp0_stage1, zext_ln373_1_fu_321_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_0_address1_local <= zext_ln373_1_fu_321_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL18eligibility_traces_0_address1_local <= zext_ln373_fu_282_p1(10 - 1 downto 0);
        else 
            p_ZL18eligibility_traces_0_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_ZL18eligibility_traces_0_ce1 <= p_ZL18eligibility_traces_0_ce1_local;

    p_ZL18eligibility_traces_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL18eligibility_traces_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_0_d1 <= ap_const_lv16_0;
    p_ZL18eligibility_traces_0_we1 <= p_ZL18eligibility_traces_0_we1_local;

    p_ZL18eligibility_traces_0_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln370_fu_208_p2, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln370_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            p_ZL18eligibility_traces_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_1_address1 <= p_ZL18eligibility_traces_1_address1_local;

    p_ZL18eligibility_traces_1_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, zext_ln373_fu_282_p1, ap_block_pp0_stage1, zext_ln373_1_fu_321_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_1_address1_local <= zext_ln373_1_fu_321_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL18eligibility_traces_1_address1_local <= zext_ln373_fu_282_p1(10 - 1 downto 0);
        else 
            p_ZL18eligibility_traces_1_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_ZL18eligibility_traces_1_ce1 <= p_ZL18eligibility_traces_1_ce1_local;

    p_ZL18eligibility_traces_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL18eligibility_traces_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_1_d1 <= ap_const_lv16_0;
    p_ZL18eligibility_traces_1_we1 <= p_ZL18eligibility_traces_1_we1_local;

    p_ZL18eligibility_traces_1_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln370_fu_208_p2, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln370_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            p_ZL18eligibility_traces_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_2_address1 <= p_ZL18eligibility_traces_2_address1_local;

    p_ZL18eligibility_traces_2_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, zext_ln373_fu_282_p1, ap_block_pp0_stage1, zext_ln373_1_fu_321_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_2_address1_local <= zext_ln373_1_fu_321_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL18eligibility_traces_2_address1_local <= zext_ln373_fu_282_p1(10 - 1 downto 0);
        else 
            p_ZL18eligibility_traces_2_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_ZL18eligibility_traces_2_ce1 <= p_ZL18eligibility_traces_2_ce1_local;

    p_ZL18eligibility_traces_2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL18eligibility_traces_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_2_d1 <= ap_const_lv16_0;
    p_ZL18eligibility_traces_2_we1 <= p_ZL18eligibility_traces_2_we1_local;

    p_ZL18eligibility_traces_2_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln370_fu_208_p2, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln370_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            p_ZL18eligibility_traces_2_we1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_3_address1 <= p_ZL18eligibility_traces_3_address1_local;

    p_ZL18eligibility_traces_3_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, zext_ln373_fu_282_p1, ap_block_pp0_stage1, zext_ln373_1_fu_321_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_3_address1_local <= zext_ln373_1_fu_321_p1(10 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL18eligibility_traces_3_address1_local <= zext_ln373_fu_282_p1(10 - 1 downto 0);
        else 
            p_ZL18eligibility_traces_3_address1_local <= "XXXXXXXXXX";
        end if; 
    end process;

    p_ZL18eligibility_traces_3_ce1 <= p_ZL18eligibility_traces_3_ce1_local;

    p_ZL18eligibility_traces_3_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL18eligibility_traces_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_3_d1 <= ap_const_lv16_0;
    p_ZL18eligibility_traces_3_we1 <= p_ZL18eligibility_traces_3_we1_local;

    p_ZL18eligibility_traces_3_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln370_fu_208_p2, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln370_fu_208_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            p_ZL18eligibility_traces_3_we1_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln370_1_fu_252_p3 <= 
        add_ln370_fu_230_p2 when (tmp_fu_236_p3(0) = '1') else 
        i_fu_78;
    select_ln370_fu_244_p3 <= 
        ap_const_lv6_0 when (tmp_fu_236_p3(0) = '1') else 
        trunc_ln370_fu_226_p1;
    tmp_8_fu_313_p4 <= ((trunc_ln371_reg_369 & tmp_7_reg_374) & ap_const_lv1_1);
    tmp_fu_236_p3 <= j_fu_74(6 downto 6);
    tmp_s_fu_274_p3 <= (trunc_ln371_fu_260_p1 & lshr_ln1_fu_264_p4);
    trunc_ln370_fu_226_p1 <= j_fu_74(6 - 1 downto 0);
    trunc_ln371_fu_260_p1 <= select_ln370_1_fu_252_p3(6 - 1 downto 0);
    zext_ln370_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln370_reg_364),7));
    zext_ln373_1_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_313_p4),64));
    zext_ln373_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_274_p3),64));
end behav;
