// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_529_110 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weight_sum_18_reload,
        weight_sum_20_out,
        weight_sum_20_out_ap_vld,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_2_address0,
        p_ZL13weight_memory_2_ce0,
        p_ZL13weight_memory_2_q0,
        p_ZL13weight_memory_3_address0,
        p_ZL13weight_memory_3_ce0,
        p_ZL13weight_memory_3_q0,
        p_ZL13weight_memory_4_address0,
        p_ZL13weight_memory_4_ce0,
        p_ZL13weight_memory_4_q0,
        p_ZL13weight_memory_5_address0,
        p_ZL13weight_memory_5_ce0,
        p_ZL13weight_memory_5_q0,
        p_ZL13weight_memory_6_address0,
        p_ZL13weight_memory_6_ce0,
        p_ZL13weight_memory_6_q0,
        p_ZL13weight_memory_7_address0,
        p_ZL13weight_memory_7_ce0,
        p_ZL13weight_memory_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] weight_sum_18_reload;
output  [15:0] weight_sum_20_out;
output   weight_sum_20_out_ap_vld;
output  [8:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [8:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [8:0] p_ZL13weight_memory_2_address0;
output   p_ZL13weight_memory_2_ce0;
input  [7:0] p_ZL13weight_memory_2_q0;
output  [8:0] p_ZL13weight_memory_3_address0;
output   p_ZL13weight_memory_3_ce0;
input  [7:0] p_ZL13weight_memory_3_q0;
output  [8:0] p_ZL13weight_memory_4_address0;
output   p_ZL13weight_memory_4_ce0;
input  [7:0] p_ZL13weight_memory_4_q0;
output  [8:0] p_ZL13weight_memory_5_address0;
output   p_ZL13weight_memory_5_ce0;
input  [7:0] p_ZL13weight_memory_5_q0;
output  [8:0] p_ZL13weight_memory_6_address0;
output   p_ZL13weight_memory_6_ce0;
input  [7:0] p_ZL13weight_memory_6_q0;
output  [8:0] p_ZL13weight_memory_7_address0;
output   p_ZL13weight_memory_7_ce0;
input  [7:0] p_ZL13weight_memory_7_q0;

reg ap_idle;
reg weight_sum_20_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln529_fu_224_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln529_reg_352;
wire   [2:0] trunc_ln529_fu_236_p1;
reg   [2:0] trunc_ln529_reg_356;
wire   [7:0] tmp_s_fu_277_p19;
reg   [7:0] tmp_s_reg_401;
wire   [63:0] zext_ln530_fu_260_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] weight_sum_fu_86;
wire   [15:0] weight_sum_12_fu_322_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [4:0] j_fu_90;
wire   [4:0] add_ln529_fu_230_p2;
reg   [4:0] ap_sig_allocacmp_j_12;
wire    ap_block_pp0_stage0_01001;
reg    p_ZL13weight_memory_0_ce0_local;
reg    p_ZL13weight_memory_1_ce0_local;
reg    p_ZL13weight_memory_2_ce0_local;
reg    p_ZL13weight_memory_3_ce0_local;
reg    p_ZL13weight_memory_4_ce0_local;
reg    p_ZL13weight_memory_5_ce0_local;
reg    p_ZL13weight_memory_6_ce0_local;
reg    p_ZL13weight_memory_7_ce0_local;
wire   [0:0] tmp_fu_240_p3;
wire   [3:0] zext_ln526_fu_248_p1;
wire   [6:0] tmp_41_cast_fu_252_p3;
wire   [7:0] tmp_s_fu_277_p17;
wire  signed [15:0] sext_ln530_fu_319_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_s_fu_277_p1;
wire   [2:0] tmp_s_fu_277_p3;
wire   [2:0] tmp_s_fu_277_p5;
wire   [2:0] tmp_s_fu_277_p7;
wire  signed [2:0] tmp_s_fu_277_p9;
wire  signed [2:0] tmp_s_fu_277_p11;
wire  signed [2:0] tmp_s_fu_277_p13;
wire  signed [2:0] tmp_s_fu_277_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 weight_sum_fu_86 = 16'd0;
#0 j_fu_90 = 5'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U371(
    .din0(p_ZL13weight_memory_0_q0),
    .din1(p_ZL13weight_memory_1_q0),
    .din2(p_ZL13weight_memory_2_q0),
    .din3(p_ZL13weight_memory_3_q0),
    .din4(p_ZL13weight_memory_4_q0),
    .din5(p_ZL13weight_memory_5_q0),
    .din6(p_ZL13weight_memory_6_q0),
    .din7(p_ZL13weight_memory_7_q0),
    .def(tmp_s_fu_277_p17),
    .sel(trunc_ln529_reg_356),
    .dout(tmp_s_fu_277_p19)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln529_fu_224_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_90 <= add_ln529_fu_230_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_90 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            weight_sum_fu_86 <= weight_sum_18_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            weight_sum_fu_86 <= weight_sum_12_fu_322_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln529_reg_352 <= icmp_ln529_fu_224_p2;
        tmp_s_reg_401 <= tmp_s_fu_277_p19;
        trunc_ln529_reg_356 <= trunc_ln529_fu_236_p1;
    end
end

always @ (*) begin
    if (((icmp_ln529_fu_224_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_12 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_12 = j_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_0_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_1_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_2_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_3_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_4_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_5_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_6_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_7_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln529_reg_352 == 1'd1))) begin
        weight_sum_20_out_ap_vld = 1'b1;
    end else begin
        weight_sum_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln529_fu_230_p2 = (ap_sig_allocacmp_j_12 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln529_fu_224_p2 = ((ap_sig_allocacmp_j_12 == 5'd16) ? 1'b1 : 1'b0);

assign p_ZL13weight_memory_0_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_0_ce0 = p_ZL13weight_memory_0_ce0_local;

assign p_ZL13weight_memory_1_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_1_ce0 = p_ZL13weight_memory_1_ce0_local;

assign p_ZL13weight_memory_2_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_2_ce0 = p_ZL13weight_memory_2_ce0_local;

assign p_ZL13weight_memory_3_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_3_ce0 = p_ZL13weight_memory_3_ce0_local;

assign p_ZL13weight_memory_4_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_4_ce0 = p_ZL13weight_memory_4_ce0_local;

assign p_ZL13weight_memory_5_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_5_ce0 = p_ZL13weight_memory_5_ce0_local;

assign p_ZL13weight_memory_6_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_6_ce0 = p_ZL13weight_memory_6_ce0_local;

assign p_ZL13weight_memory_7_address0 = zext_ln530_fu_260_p1;

assign p_ZL13weight_memory_7_ce0 = p_ZL13weight_memory_7_ce0_local;

assign sext_ln530_fu_319_p1 = $signed(tmp_s_reg_401);

assign tmp_41_cast_fu_252_p3 = {{3'd5}, {zext_ln526_fu_248_p1}};

assign tmp_fu_240_p3 = ap_sig_allocacmp_j_12[32'd3];

assign tmp_s_fu_277_p17 = 'bx;

assign trunc_ln529_fu_236_p1 = ap_sig_allocacmp_j_12[2:0];

assign weight_sum_12_fu_322_p2 = ($signed(sext_ln530_fu_319_p1) + $signed(weight_sum_fu_86));

assign weight_sum_20_out = weight_sum_fu_86;

assign zext_ln526_fu_248_p1 = tmp_fu_240_p3;

assign zext_ln530_fu_260_p1 = tmp_41_cast_fu_252_p3;

endmodule //snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_529_110
