-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_snn_top_hls_Pipeline_RESET_PRE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL15pre_spike_times_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_0_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_0_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_1_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_1_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_2_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_2_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_3_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_3_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_4_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_4_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_5_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_5_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_6_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_6_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL15pre_spike_times_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL15pre_spike_times_7_ce0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_7_we0 : OUT STD_LOGIC;
    p_ZL15pre_spike_times_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_0_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_0_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_1_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_1_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_2_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_2_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_3_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_3_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_4_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_4_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_5_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_5_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_6_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_6_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_ZL16post_spike_times_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_ZL16post_spike_times_7_ce0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_7_we0 : OUT STD_LOGIC;
    p_ZL16post_spike_times_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of snn_top_hls_snn_top_hls_Pipeline_RESET_PRE is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_fu_312_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln363_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_76 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln363_fu_350_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_spike_times_0_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_0_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_1_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_1_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_2_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_2_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_3_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_3_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_4_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_4_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_5_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_5_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_6_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_6_ce0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_7_we0_local : STD_LOGIC;
    signal p_ZL15pre_spike_times_7_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_0_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_0_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_1_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_1_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_2_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_2_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_3_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_3_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_4_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_4_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_5_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_5_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_6_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_6_ce0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_7_we0_local : STD_LOGIC;
    signal p_ZL16post_spike_times_7_ce0_local : STD_LOGIC;
    signal lshr_ln_fu_320_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((tmp_fu_312_p3 = ap_const_lv1_0)) then 
                    i_fu_76 <= add_ln363_fu_350_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_76 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln363_fu_350_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv7_8));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_state1, i_fu_76, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_76;
        end if; 
    end process;

    lshr_ln_fu_320_p4 <= ap_sig_allocacmp_i_1(5 downto 3);
    p_ZL15pre_spike_times_0_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_0_ce0 <= p_ZL15pre_spike_times_0_ce0_local;

    p_ZL15pre_spike_times_0_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_0_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_0_we0 <= p_ZL15pre_spike_times_0_we0_local;

    p_ZL15pre_spike_times_0_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_0_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_1_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_1_ce0 <= p_ZL15pre_spike_times_1_ce0_local;

    p_ZL15pre_spike_times_1_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_1_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_1_we0 <= p_ZL15pre_spike_times_1_we0_local;

    p_ZL15pre_spike_times_1_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_1_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_2_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_2_ce0 <= p_ZL15pre_spike_times_2_ce0_local;

    p_ZL15pre_spike_times_2_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_2_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_2_we0 <= p_ZL15pre_spike_times_2_we0_local;

    p_ZL15pre_spike_times_2_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_2_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_3_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_3_ce0 <= p_ZL15pre_spike_times_3_ce0_local;

    p_ZL15pre_spike_times_3_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_3_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_3_we0 <= p_ZL15pre_spike_times_3_we0_local;

    p_ZL15pre_spike_times_3_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_3_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_4_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_4_ce0 <= p_ZL15pre_spike_times_4_ce0_local;

    p_ZL15pre_spike_times_4_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_4_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_4_we0 <= p_ZL15pre_spike_times_4_we0_local;

    p_ZL15pre_spike_times_4_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_4_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_5_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_5_ce0 <= p_ZL15pre_spike_times_5_ce0_local;

    p_ZL15pre_spike_times_5_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_5_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_5_we0 <= p_ZL15pre_spike_times_5_we0_local;

    p_ZL15pre_spike_times_5_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_5_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_6_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_6_ce0 <= p_ZL15pre_spike_times_6_ce0_local;

    p_ZL15pre_spike_times_6_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_6_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_6_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_6_we0 <= p_ZL15pre_spike_times_6_we0_local;

    p_ZL15pre_spike_times_6_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_6_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_7_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL15pre_spike_times_7_ce0 <= p_ZL15pre_spike_times_7_ce0_local;

    p_ZL15pre_spike_times_7_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_7_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_spike_times_7_d0 <= ap_const_lv32_0;
    p_ZL15pre_spike_times_7_we0 <= p_ZL15pre_spike_times_7_we0_local;

    p_ZL15pre_spike_times_7_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL15pre_spike_times_7_we0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_spike_times_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_0_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_0_ce0 <= p_ZL16post_spike_times_0_ce0_local;

    p_ZL16post_spike_times_0_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_0_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_0_we0 <= p_ZL16post_spike_times_0_we0_local;

    p_ZL16post_spike_times_0_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_0_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_1_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_1_ce0 <= p_ZL16post_spike_times_1_ce0_local;

    p_ZL16post_spike_times_1_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_1_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_1_we0 <= p_ZL16post_spike_times_1_we0_local;

    p_ZL16post_spike_times_1_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_1_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_2_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_2_ce0 <= p_ZL16post_spike_times_2_ce0_local;

    p_ZL16post_spike_times_2_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_2_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_2_we0 <= p_ZL16post_spike_times_2_we0_local;

    p_ZL16post_spike_times_2_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_2_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_3_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_3_ce0 <= p_ZL16post_spike_times_3_ce0_local;

    p_ZL16post_spike_times_3_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_3_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_3_we0 <= p_ZL16post_spike_times_3_we0_local;

    p_ZL16post_spike_times_3_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_3_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_4_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_4_ce0 <= p_ZL16post_spike_times_4_ce0_local;

    p_ZL16post_spike_times_4_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_4_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_4_we0 <= p_ZL16post_spike_times_4_we0_local;

    p_ZL16post_spike_times_4_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_4_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_5_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_5_ce0 <= p_ZL16post_spike_times_5_ce0_local;

    p_ZL16post_spike_times_5_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_5_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_5_we0 <= p_ZL16post_spike_times_5_we0_local;

    p_ZL16post_spike_times_5_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_5_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_6_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_6_ce0 <= p_ZL16post_spike_times_6_ce0_local;

    p_ZL16post_spike_times_6_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_6_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_6_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_6_we0 <= p_ZL16post_spike_times_6_we0_local;

    p_ZL16post_spike_times_6_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_6_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_7_address0 <= zext_ln363_fu_330_p1(3 - 1 downto 0);
    p_ZL16post_spike_times_7_ce0 <= p_ZL16post_spike_times_7_ce0_local;

    p_ZL16post_spike_times_7_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_7_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_spike_times_7_d0 <= ap_const_lv32_0;
    p_ZL16post_spike_times_7_we0 <= p_ZL16post_spike_times_7_we0_local;

    p_ZL16post_spike_times_7_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_312_p3)
    begin
        if (((tmp_fu_312_p3 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_ZL16post_spike_times_7_we0_local <= ap_const_logic_1;
        else 
            p_ZL16post_spike_times_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_312_p3 <= ap_sig_allocacmp_i_1(6 downto 6);
    zext_ln363_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_320_p4),64));
end behav;
