// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_apply_reward_signal (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reward_signal,
        params_learning_rate_val,
        p_ZL18eligibility_traces_0_address0,
        p_ZL18eligibility_traces_0_ce0,
        p_ZL18eligibility_traces_0_q0,
        p_ZL18eligibility_traces_1_address0,
        p_ZL18eligibility_traces_1_ce0,
        p_ZL18eligibility_traces_1_q0,
        p_ZL18eligibility_traces_2_address0,
        p_ZL18eligibility_traces_2_ce0,
        p_ZL18eligibility_traces_2_q0,
        p_ZL18eligibility_traces_3_address0,
        p_ZL18eligibility_traces_3_ce0,
        p_ZL18eligibility_traces_3_q0,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_we1,
        p_ZL13weight_memory_0_d1,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_we1,
        p_ZL13weight_memory_1_d1,
        p_ZL13weight_memory_2_address0,
        p_ZL13weight_memory_2_ce0,
        p_ZL13weight_memory_2_q0,
        p_ZL13weight_memory_2_address1,
        p_ZL13weight_memory_2_ce1,
        p_ZL13weight_memory_2_we1,
        p_ZL13weight_memory_2_d1,
        p_ZL13weight_memory_3_address0,
        p_ZL13weight_memory_3_ce0,
        p_ZL13weight_memory_3_q0,
        p_ZL13weight_memory_3_address1,
        p_ZL13weight_memory_3_ce1,
        p_ZL13weight_memory_3_we1,
        p_ZL13weight_memory_3_d1,
        p_ZL13weight_memory_4_address0,
        p_ZL13weight_memory_4_ce0,
        p_ZL13weight_memory_4_q0,
        p_ZL13weight_memory_4_address1,
        p_ZL13weight_memory_4_ce1,
        p_ZL13weight_memory_4_we1,
        p_ZL13weight_memory_4_d1,
        p_ZL13weight_memory_5_address0,
        p_ZL13weight_memory_5_ce0,
        p_ZL13weight_memory_5_q0,
        p_ZL13weight_memory_5_address1,
        p_ZL13weight_memory_5_ce1,
        p_ZL13weight_memory_5_we1,
        p_ZL13weight_memory_5_d1,
        p_ZL13weight_memory_6_address0,
        p_ZL13weight_memory_6_ce0,
        p_ZL13weight_memory_6_q0,
        p_ZL13weight_memory_6_address1,
        p_ZL13weight_memory_6_ce1,
        p_ZL13weight_memory_6_we1,
        p_ZL13weight_memory_6_d1,
        p_ZL13weight_memory_7_address0,
        p_ZL13weight_memory_7_ce0,
        p_ZL13weight_memory_7_q0,
        p_ZL13weight_memory_7_address1,
        p_ZL13weight_memory_7_ce1,
        p_ZL13weight_memory_7_we1,
        p_ZL13weight_memory_7_d1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] reward_signal;
input  [15:0] params_learning_rate_val;
output  [9:0] p_ZL18eligibility_traces_0_address0;
output   p_ZL18eligibility_traces_0_ce0;
input  [15:0] p_ZL18eligibility_traces_0_q0;
output  [9:0] p_ZL18eligibility_traces_1_address0;
output   p_ZL18eligibility_traces_1_ce0;
input  [15:0] p_ZL18eligibility_traces_1_q0;
output  [9:0] p_ZL18eligibility_traces_2_address0;
output   p_ZL18eligibility_traces_2_ce0;
input  [15:0] p_ZL18eligibility_traces_2_q0;
output  [9:0] p_ZL18eligibility_traces_3_address0;
output   p_ZL18eligibility_traces_3_ce0;
input  [15:0] p_ZL18eligibility_traces_3_q0;
output  [8:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [8:0] p_ZL13weight_memory_0_address1;
output   p_ZL13weight_memory_0_ce1;
output   p_ZL13weight_memory_0_we1;
output  [7:0] p_ZL13weight_memory_0_d1;
output  [8:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [8:0] p_ZL13weight_memory_1_address1;
output   p_ZL13weight_memory_1_ce1;
output   p_ZL13weight_memory_1_we1;
output  [7:0] p_ZL13weight_memory_1_d1;
output  [8:0] p_ZL13weight_memory_2_address0;
output   p_ZL13weight_memory_2_ce0;
input  [7:0] p_ZL13weight_memory_2_q0;
output  [8:0] p_ZL13weight_memory_2_address1;
output   p_ZL13weight_memory_2_ce1;
output   p_ZL13weight_memory_2_we1;
output  [7:0] p_ZL13weight_memory_2_d1;
output  [8:0] p_ZL13weight_memory_3_address0;
output   p_ZL13weight_memory_3_ce0;
input  [7:0] p_ZL13weight_memory_3_q0;
output  [8:0] p_ZL13weight_memory_3_address1;
output   p_ZL13weight_memory_3_ce1;
output   p_ZL13weight_memory_3_we1;
output  [7:0] p_ZL13weight_memory_3_d1;
output  [8:0] p_ZL13weight_memory_4_address0;
output   p_ZL13weight_memory_4_ce0;
input  [7:0] p_ZL13weight_memory_4_q0;
output  [8:0] p_ZL13weight_memory_4_address1;
output   p_ZL13weight_memory_4_ce1;
output   p_ZL13weight_memory_4_we1;
output  [7:0] p_ZL13weight_memory_4_d1;
output  [8:0] p_ZL13weight_memory_5_address0;
output   p_ZL13weight_memory_5_ce0;
input  [7:0] p_ZL13weight_memory_5_q0;
output  [8:0] p_ZL13weight_memory_5_address1;
output   p_ZL13weight_memory_5_ce1;
output   p_ZL13weight_memory_5_we1;
output  [7:0] p_ZL13weight_memory_5_d1;
output  [8:0] p_ZL13weight_memory_6_address0;
output   p_ZL13weight_memory_6_ce0;
input  [7:0] p_ZL13weight_memory_6_q0;
output  [8:0] p_ZL13weight_memory_6_address1;
output   p_ZL13weight_memory_6_ce1;
output   p_ZL13weight_memory_6_we1;
output  [7:0] p_ZL13weight_memory_6_d1;
output  [8:0] p_ZL13weight_memory_7_address0;
output   p_ZL13weight_memory_7_ce0;
input  [7:0] p_ZL13weight_memory_7_q0;
output  [8:0] p_ZL13weight_memory_7_address1;
output   p_ZL13weight_memory_7_ce1;
output   p_ZL13weight_memory_7_we1;
output  [7:0] p_ZL13weight_memory_7_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln219_fu_109_p2;
reg   [0:0] icmp_ln219_reg_183;
wire   [9:0] reward_factor_fu_169_p3;
reg   [9:0] reward_factor_reg_187;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_idle;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_ready;
wire   [9:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_ce0;
wire   [9:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_ce0;
wire   [9:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_ce0;
wire   [9:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_d1;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address0;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce0;
wire   [8:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce1;
wire    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_we1;
wire   [7:0] grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_d1;
reg    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [23:0] shl_ln221_1_fu_115_p3;
wire  signed [24:0] sext_ln221_fu_123_p1;
wire   [8:0] shl_ln221_2_fu_141_p3;
wire  signed [9:0] sext_ln221_1_fu_149_p1;
wire   [24:0] sub_ln221_fu_135_p2;
wire   [0:0] tmp_fu_127_p3;
wire   [9:0] tmp_s_fu_159_p4;
wire   [9:0] sub_ln221_1_fu_153_p2;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg = 1'b0;
end

snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start),
    .ap_done(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done),
    .ap_idle(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_idle),
    .ap_ready(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_ready),
    .sext_ln230(reward_factor_reg_187),
    .sext_ln223(params_learning_rate_val),
    .p_ZL18eligibility_traces_0_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_address0),
    .p_ZL18eligibility_traces_0_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_ce0),
    .p_ZL18eligibility_traces_0_q0(p_ZL18eligibility_traces_0_q0),
    .p_ZL18eligibility_traces_1_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_address0),
    .p_ZL18eligibility_traces_1_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_ce0),
    .p_ZL18eligibility_traces_1_q0(p_ZL18eligibility_traces_1_q0),
    .p_ZL18eligibility_traces_2_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_address0),
    .p_ZL18eligibility_traces_2_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_ce0),
    .p_ZL18eligibility_traces_2_q0(p_ZL18eligibility_traces_2_q0),
    .p_ZL18eligibility_traces_3_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_address0),
    .p_ZL18eligibility_traces_3_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_ce0),
    .p_ZL18eligibility_traces_3_q0(p_ZL18eligibility_traces_3_q0),
    .p_ZL13weight_memory_0_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address0),
    .p_ZL13weight_memory_0_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce0),
    .p_ZL13weight_memory_0_q0(p_ZL13weight_memory_0_q0),
    .p_ZL13weight_memory_0_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address1),
    .p_ZL13weight_memory_0_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce1),
    .p_ZL13weight_memory_0_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_we1),
    .p_ZL13weight_memory_0_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_d1),
    .p_ZL13weight_memory_1_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address0),
    .p_ZL13weight_memory_1_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce0),
    .p_ZL13weight_memory_1_q0(p_ZL13weight_memory_1_q0),
    .p_ZL13weight_memory_1_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address1),
    .p_ZL13weight_memory_1_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce1),
    .p_ZL13weight_memory_1_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_we1),
    .p_ZL13weight_memory_1_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_d1),
    .p_ZL13weight_memory_2_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address0),
    .p_ZL13weight_memory_2_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce0),
    .p_ZL13weight_memory_2_q0(p_ZL13weight_memory_2_q0),
    .p_ZL13weight_memory_2_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address1),
    .p_ZL13weight_memory_2_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce1),
    .p_ZL13weight_memory_2_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_we1),
    .p_ZL13weight_memory_2_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_d1),
    .p_ZL13weight_memory_3_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address0),
    .p_ZL13weight_memory_3_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce0),
    .p_ZL13weight_memory_3_q0(p_ZL13weight_memory_3_q0),
    .p_ZL13weight_memory_3_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address1),
    .p_ZL13weight_memory_3_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce1),
    .p_ZL13weight_memory_3_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_we1),
    .p_ZL13weight_memory_3_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_d1),
    .p_ZL13weight_memory_4_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address0),
    .p_ZL13weight_memory_4_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce0),
    .p_ZL13weight_memory_4_q0(p_ZL13weight_memory_4_q0),
    .p_ZL13weight_memory_4_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address1),
    .p_ZL13weight_memory_4_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce1),
    .p_ZL13weight_memory_4_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_we1),
    .p_ZL13weight_memory_4_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_d1),
    .p_ZL13weight_memory_5_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address0),
    .p_ZL13weight_memory_5_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce0),
    .p_ZL13weight_memory_5_q0(p_ZL13weight_memory_5_q0),
    .p_ZL13weight_memory_5_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address1),
    .p_ZL13weight_memory_5_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce1),
    .p_ZL13weight_memory_5_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_we1),
    .p_ZL13weight_memory_5_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_d1),
    .p_ZL13weight_memory_6_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address0),
    .p_ZL13weight_memory_6_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce0),
    .p_ZL13weight_memory_6_q0(p_ZL13weight_memory_6_q0),
    .p_ZL13weight_memory_6_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address1),
    .p_ZL13weight_memory_6_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce1),
    .p_ZL13weight_memory_6_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_we1),
    .p_ZL13weight_memory_6_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_d1),
    .p_ZL13weight_memory_7_address0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address0),
    .p_ZL13weight_memory_7_ce0(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce0),
    .p_ZL13weight_memory_7_q0(p_ZL13weight_memory_7_q0),
    .p_ZL13weight_memory_7_address1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address1),
    .p_ZL13weight_memory_7_ce1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce1),
    .p_ZL13weight_memory_7_we1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_we1),
    .p_ZL13weight_memory_7_d1(grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln219_fu_109_p2 == 1'd0))) begin
            grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_ready == 1'b1)) begin
            grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln219_reg_183 <= icmp_ln219_fu_109_p2;
        reward_factor_reg_187[9 : 1] <= reward_factor_fu_169_p3[9 : 1];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done == 1'b0) & (icmp_ln219_reg_183 == 1'd0));
end

assign grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg;

assign icmp_ln219_fu_109_p2 = ((reward_signal == 8'd0) ? 1'b1 : 1'b0);

assign p_ZL13weight_memory_0_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address0;

assign p_ZL13weight_memory_0_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address1;

assign p_ZL13weight_memory_0_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce0;

assign p_ZL13weight_memory_0_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce1;

assign p_ZL13weight_memory_0_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_d1;

assign p_ZL13weight_memory_0_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_we1;

assign p_ZL13weight_memory_1_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address0;

assign p_ZL13weight_memory_1_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address1;

assign p_ZL13weight_memory_1_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce0;

assign p_ZL13weight_memory_1_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce1;

assign p_ZL13weight_memory_1_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_d1;

assign p_ZL13weight_memory_1_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_we1;

assign p_ZL13weight_memory_2_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address0;

assign p_ZL13weight_memory_2_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address1;

assign p_ZL13weight_memory_2_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce0;

assign p_ZL13weight_memory_2_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce1;

assign p_ZL13weight_memory_2_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_d1;

assign p_ZL13weight_memory_2_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_we1;

assign p_ZL13weight_memory_3_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address0;

assign p_ZL13weight_memory_3_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address1;

assign p_ZL13weight_memory_3_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce0;

assign p_ZL13weight_memory_3_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce1;

assign p_ZL13weight_memory_3_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_d1;

assign p_ZL13weight_memory_3_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_we1;

assign p_ZL13weight_memory_4_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address0;

assign p_ZL13weight_memory_4_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address1;

assign p_ZL13weight_memory_4_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce0;

assign p_ZL13weight_memory_4_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce1;

assign p_ZL13weight_memory_4_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_d1;

assign p_ZL13weight_memory_4_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_we1;

assign p_ZL13weight_memory_5_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address0;

assign p_ZL13weight_memory_5_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address1;

assign p_ZL13weight_memory_5_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce0;

assign p_ZL13weight_memory_5_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce1;

assign p_ZL13weight_memory_5_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_d1;

assign p_ZL13weight_memory_5_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_we1;

assign p_ZL13weight_memory_6_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address0;

assign p_ZL13weight_memory_6_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address1;

assign p_ZL13weight_memory_6_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce0;

assign p_ZL13weight_memory_6_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce1;

assign p_ZL13weight_memory_6_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_d1;

assign p_ZL13weight_memory_6_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_we1;

assign p_ZL13weight_memory_7_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address0;

assign p_ZL13weight_memory_7_address1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address1;

assign p_ZL13weight_memory_7_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce0;

assign p_ZL13weight_memory_7_ce1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce1;

assign p_ZL13weight_memory_7_d1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_d1;

assign p_ZL13weight_memory_7_we1 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_we1;

assign p_ZL18eligibility_traces_0_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_address0;

assign p_ZL18eligibility_traces_0_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_ce0;

assign p_ZL18eligibility_traces_1_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_address0;

assign p_ZL18eligibility_traces_1_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_ce0;

assign p_ZL18eligibility_traces_2_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_address0;

assign p_ZL18eligibility_traces_2_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_ce0;

assign p_ZL18eligibility_traces_3_address0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_address0;

assign p_ZL18eligibility_traces_3_ce0 = grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_ce0;

assign reward_factor_fu_169_p3 = ((tmp_fu_127_p3[0:0] == 1'b1) ? tmp_s_fu_159_p4 : sub_ln221_1_fu_153_p2);

assign sext_ln221_1_fu_149_p1 = $signed(shl_ln221_2_fu_141_p3);

assign sext_ln221_fu_123_p1 = $signed(shl_ln221_1_fu_115_p3);

assign shl_ln221_1_fu_115_p3 = {{reward_signal}, {16'd0}};

assign shl_ln221_2_fu_141_p3 = {{reward_signal}, {1'd0}};

assign sub_ln221_1_fu_153_p2 = ($signed(10'd0) - $signed(sext_ln221_1_fu_149_p1));

assign sub_ln221_fu_135_p2 = ($signed(25'd0) - $signed(sext_ln221_fu_123_p1));

assign tmp_fu_127_p3 = reward_signal[32'd7];

assign tmp_s_fu_159_p4 = {{sub_ln221_fu_135_p2[24:15]}};

always @ (posedge ap_clk) begin
    reward_factor_reg_187[0] <= 1'b0;
end

endmodule //snn_top_hls_apply_reward_signal
