// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_RESET_PRE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZL15pre_spike_times_0_address0,
        p_ZL15pre_spike_times_0_ce0,
        p_ZL15pre_spike_times_0_we0,
        p_ZL15pre_spike_times_0_d0,
        p_ZL15pre_spike_times_1_address0,
        p_ZL15pre_spike_times_1_ce0,
        p_ZL15pre_spike_times_1_we0,
        p_ZL15pre_spike_times_1_d0,
        p_ZL15pre_spike_times_2_address0,
        p_ZL15pre_spike_times_2_ce0,
        p_ZL15pre_spike_times_2_we0,
        p_ZL15pre_spike_times_2_d0,
        p_ZL15pre_spike_times_3_address0,
        p_ZL15pre_spike_times_3_ce0,
        p_ZL15pre_spike_times_3_we0,
        p_ZL15pre_spike_times_3_d0,
        p_ZL15pre_spike_times_4_address0,
        p_ZL15pre_spike_times_4_ce0,
        p_ZL15pre_spike_times_4_we0,
        p_ZL15pre_spike_times_4_d0,
        p_ZL15pre_spike_times_5_address0,
        p_ZL15pre_spike_times_5_ce0,
        p_ZL15pre_spike_times_5_we0,
        p_ZL15pre_spike_times_5_d0,
        p_ZL15pre_spike_times_6_address0,
        p_ZL15pre_spike_times_6_ce0,
        p_ZL15pre_spike_times_6_we0,
        p_ZL15pre_spike_times_6_d0,
        p_ZL15pre_spike_times_7_address0,
        p_ZL15pre_spike_times_7_ce0,
        p_ZL15pre_spike_times_7_we0,
        p_ZL15pre_spike_times_7_d0,
        p_ZL16post_spike_times_0_address0,
        p_ZL16post_spike_times_0_ce0,
        p_ZL16post_spike_times_0_we0,
        p_ZL16post_spike_times_0_d0,
        p_ZL16post_spike_times_1_address0,
        p_ZL16post_spike_times_1_ce0,
        p_ZL16post_spike_times_1_we0,
        p_ZL16post_spike_times_1_d0,
        p_ZL16post_spike_times_2_address0,
        p_ZL16post_spike_times_2_ce0,
        p_ZL16post_spike_times_2_we0,
        p_ZL16post_spike_times_2_d0,
        p_ZL16post_spike_times_3_address0,
        p_ZL16post_spike_times_3_ce0,
        p_ZL16post_spike_times_3_we0,
        p_ZL16post_spike_times_3_d0,
        p_ZL16post_spike_times_4_address0,
        p_ZL16post_spike_times_4_ce0,
        p_ZL16post_spike_times_4_we0,
        p_ZL16post_spike_times_4_d0,
        p_ZL16post_spike_times_5_address0,
        p_ZL16post_spike_times_5_ce0,
        p_ZL16post_spike_times_5_we0,
        p_ZL16post_spike_times_5_d0,
        p_ZL16post_spike_times_6_address0,
        p_ZL16post_spike_times_6_ce0,
        p_ZL16post_spike_times_6_we0,
        p_ZL16post_spike_times_6_d0,
        p_ZL16post_spike_times_7_address0,
        p_ZL16post_spike_times_7_ce0,
        p_ZL16post_spike_times_7_we0,
        p_ZL16post_spike_times_7_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] p_ZL15pre_spike_times_0_address0;
output   p_ZL15pre_spike_times_0_ce0;
output   p_ZL15pre_spike_times_0_we0;
output  [31:0] p_ZL15pre_spike_times_0_d0;
output  [2:0] p_ZL15pre_spike_times_1_address0;
output   p_ZL15pre_spike_times_1_ce0;
output   p_ZL15pre_spike_times_1_we0;
output  [31:0] p_ZL15pre_spike_times_1_d0;
output  [2:0] p_ZL15pre_spike_times_2_address0;
output   p_ZL15pre_spike_times_2_ce0;
output   p_ZL15pre_spike_times_2_we0;
output  [31:0] p_ZL15pre_spike_times_2_d0;
output  [2:0] p_ZL15pre_spike_times_3_address0;
output   p_ZL15pre_spike_times_3_ce0;
output   p_ZL15pre_spike_times_3_we0;
output  [31:0] p_ZL15pre_spike_times_3_d0;
output  [2:0] p_ZL15pre_spike_times_4_address0;
output   p_ZL15pre_spike_times_4_ce0;
output   p_ZL15pre_spike_times_4_we0;
output  [31:0] p_ZL15pre_spike_times_4_d0;
output  [2:0] p_ZL15pre_spike_times_5_address0;
output   p_ZL15pre_spike_times_5_ce0;
output   p_ZL15pre_spike_times_5_we0;
output  [31:0] p_ZL15pre_spike_times_5_d0;
output  [2:0] p_ZL15pre_spike_times_6_address0;
output   p_ZL15pre_spike_times_6_ce0;
output   p_ZL15pre_spike_times_6_we0;
output  [31:0] p_ZL15pre_spike_times_6_d0;
output  [2:0] p_ZL15pre_spike_times_7_address0;
output   p_ZL15pre_spike_times_7_ce0;
output   p_ZL15pre_spike_times_7_we0;
output  [31:0] p_ZL15pre_spike_times_7_d0;
output  [2:0] p_ZL16post_spike_times_0_address0;
output   p_ZL16post_spike_times_0_ce0;
output   p_ZL16post_spike_times_0_we0;
output  [31:0] p_ZL16post_spike_times_0_d0;
output  [2:0] p_ZL16post_spike_times_1_address0;
output   p_ZL16post_spike_times_1_ce0;
output   p_ZL16post_spike_times_1_we0;
output  [31:0] p_ZL16post_spike_times_1_d0;
output  [2:0] p_ZL16post_spike_times_2_address0;
output   p_ZL16post_spike_times_2_ce0;
output   p_ZL16post_spike_times_2_we0;
output  [31:0] p_ZL16post_spike_times_2_d0;
output  [2:0] p_ZL16post_spike_times_3_address0;
output   p_ZL16post_spike_times_3_ce0;
output   p_ZL16post_spike_times_3_we0;
output  [31:0] p_ZL16post_spike_times_3_d0;
output  [2:0] p_ZL16post_spike_times_4_address0;
output   p_ZL16post_spike_times_4_ce0;
output   p_ZL16post_spike_times_4_we0;
output  [31:0] p_ZL16post_spike_times_4_d0;
output  [2:0] p_ZL16post_spike_times_5_address0;
output   p_ZL16post_spike_times_5_ce0;
output   p_ZL16post_spike_times_5_we0;
output  [31:0] p_ZL16post_spike_times_5_d0;
output  [2:0] p_ZL16post_spike_times_6_address0;
output   p_ZL16post_spike_times_6_ce0;
output   p_ZL16post_spike_times_6_we0;
output  [31:0] p_ZL16post_spike_times_6_d0;
output  [2:0] p_ZL16post_spike_times_7_address0;
output   p_ZL16post_spike_times_7_ce0;
output   p_ZL16post_spike_times_7_we0;
output  [31:0] p_ZL16post_spike_times_7_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_fu_312_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln363_fu_330_p1;
reg   [6:0] i_fu_76;
wire   [6:0] add_ln363_fu_350_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
reg    p_ZL15pre_spike_times_0_we0_local;
reg    p_ZL15pre_spike_times_0_ce0_local;
reg    p_ZL15pre_spike_times_1_we0_local;
reg    p_ZL15pre_spike_times_1_ce0_local;
reg    p_ZL15pre_spike_times_2_we0_local;
reg    p_ZL15pre_spike_times_2_ce0_local;
reg    p_ZL15pre_spike_times_3_we0_local;
reg    p_ZL15pre_spike_times_3_ce0_local;
reg    p_ZL15pre_spike_times_4_we0_local;
reg    p_ZL15pre_spike_times_4_ce0_local;
reg    p_ZL15pre_spike_times_5_we0_local;
reg    p_ZL15pre_spike_times_5_ce0_local;
reg    p_ZL15pre_spike_times_6_we0_local;
reg    p_ZL15pre_spike_times_6_ce0_local;
reg    p_ZL15pre_spike_times_7_we0_local;
reg    p_ZL15pre_spike_times_7_ce0_local;
reg    p_ZL16post_spike_times_0_we0_local;
reg    p_ZL16post_spike_times_0_ce0_local;
reg    p_ZL16post_spike_times_1_we0_local;
reg    p_ZL16post_spike_times_1_ce0_local;
reg    p_ZL16post_spike_times_2_we0_local;
reg    p_ZL16post_spike_times_2_ce0_local;
reg    p_ZL16post_spike_times_3_we0_local;
reg    p_ZL16post_spike_times_3_ce0_local;
reg    p_ZL16post_spike_times_4_we0_local;
reg    p_ZL16post_spike_times_4_ce0_local;
reg    p_ZL16post_spike_times_5_we0_local;
reg    p_ZL16post_spike_times_5_ce0_local;
reg    p_ZL16post_spike_times_6_we0_local;
reg    p_ZL16post_spike_times_6_ce0_local;
reg    p_ZL16post_spike_times_7_we0_local;
reg    p_ZL16post_spike_times_7_ce0_local;
wire   [2:0] lshr_ln_fu_320_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_76 = 7'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((tmp_fu_312_p3 == 1'd0)) begin
            i_fu_76 <= add_ln363_fu_350_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_0_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_0_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_1_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_1_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_2_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_2_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_3_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_3_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_4_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_4_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_5_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_5_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_6_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_6_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_7_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_7_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_0_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_0_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_1_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_1_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_2_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_2_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_3_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_3_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_4_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_4_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_5_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_5_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_6_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_6_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_7_ce0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_312_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_spike_times_7_we0_local = 1'b1;
    end else begin
        p_ZL16post_spike_times_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln363_fu_350_p2 = (ap_sig_allocacmp_i_1 + 7'd8);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign lshr_ln_fu_320_p4 = {{ap_sig_allocacmp_i_1[5:3]}};

assign p_ZL15pre_spike_times_0_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_0_ce0 = p_ZL15pre_spike_times_0_ce0_local;

assign p_ZL15pre_spike_times_0_d0 = 32'd0;

assign p_ZL15pre_spike_times_0_we0 = p_ZL15pre_spike_times_0_we0_local;

assign p_ZL15pre_spike_times_1_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_1_ce0 = p_ZL15pre_spike_times_1_ce0_local;

assign p_ZL15pre_spike_times_1_d0 = 32'd0;

assign p_ZL15pre_spike_times_1_we0 = p_ZL15pre_spike_times_1_we0_local;

assign p_ZL15pre_spike_times_2_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_2_ce0 = p_ZL15pre_spike_times_2_ce0_local;

assign p_ZL15pre_spike_times_2_d0 = 32'd0;

assign p_ZL15pre_spike_times_2_we0 = p_ZL15pre_spike_times_2_we0_local;

assign p_ZL15pre_spike_times_3_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_3_ce0 = p_ZL15pre_spike_times_3_ce0_local;

assign p_ZL15pre_spike_times_3_d0 = 32'd0;

assign p_ZL15pre_spike_times_3_we0 = p_ZL15pre_spike_times_3_we0_local;

assign p_ZL15pre_spike_times_4_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_4_ce0 = p_ZL15pre_spike_times_4_ce0_local;

assign p_ZL15pre_spike_times_4_d0 = 32'd0;

assign p_ZL15pre_spike_times_4_we0 = p_ZL15pre_spike_times_4_we0_local;

assign p_ZL15pre_spike_times_5_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_5_ce0 = p_ZL15pre_spike_times_5_ce0_local;

assign p_ZL15pre_spike_times_5_d0 = 32'd0;

assign p_ZL15pre_spike_times_5_we0 = p_ZL15pre_spike_times_5_we0_local;

assign p_ZL15pre_spike_times_6_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_6_ce0 = p_ZL15pre_spike_times_6_ce0_local;

assign p_ZL15pre_spike_times_6_d0 = 32'd0;

assign p_ZL15pre_spike_times_6_we0 = p_ZL15pre_spike_times_6_we0_local;

assign p_ZL15pre_spike_times_7_address0 = zext_ln363_fu_330_p1;

assign p_ZL15pre_spike_times_7_ce0 = p_ZL15pre_spike_times_7_ce0_local;

assign p_ZL15pre_spike_times_7_d0 = 32'd0;

assign p_ZL15pre_spike_times_7_we0 = p_ZL15pre_spike_times_7_we0_local;

assign p_ZL16post_spike_times_0_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_0_ce0 = p_ZL16post_spike_times_0_ce0_local;

assign p_ZL16post_spike_times_0_d0 = 32'd0;

assign p_ZL16post_spike_times_0_we0 = p_ZL16post_spike_times_0_we0_local;

assign p_ZL16post_spike_times_1_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_1_ce0 = p_ZL16post_spike_times_1_ce0_local;

assign p_ZL16post_spike_times_1_d0 = 32'd0;

assign p_ZL16post_spike_times_1_we0 = p_ZL16post_spike_times_1_we0_local;

assign p_ZL16post_spike_times_2_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_2_ce0 = p_ZL16post_spike_times_2_ce0_local;

assign p_ZL16post_spike_times_2_d0 = 32'd0;

assign p_ZL16post_spike_times_2_we0 = p_ZL16post_spike_times_2_we0_local;

assign p_ZL16post_spike_times_3_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_3_ce0 = p_ZL16post_spike_times_3_ce0_local;

assign p_ZL16post_spike_times_3_d0 = 32'd0;

assign p_ZL16post_spike_times_3_we0 = p_ZL16post_spike_times_3_we0_local;

assign p_ZL16post_spike_times_4_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_4_ce0 = p_ZL16post_spike_times_4_ce0_local;

assign p_ZL16post_spike_times_4_d0 = 32'd0;

assign p_ZL16post_spike_times_4_we0 = p_ZL16post_spike_times_4_we0_local;

assign p_ZL16post_spike_times_5_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_5_ce0 = p_ZL16post_spike_times_5_ce0_local;

assign p_ZL16post_spike_times_5_d0 = 32'd0;

assign p_ZL16post_spike_times_5_we0 = p_ZL16post_spike_times_5_we0_local;

assign p_ZL16post_spike_times_6_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_6_ce0 = p_ZL16post_spike_times_6_ce0_local;

assign p_ZL16post_spike_times_6_d0 = 32'd0;

assign p_ZL16post_spike_times_6_we0 = p_ZL16post_spike_times_6_we0_local;

assign p_ZL16post_spike_times_7_address0 = zext_ln363_fu_330_p1;

assign p_ZL16post_spike_times_7_ce0 = p_ZL16post_spike_times_7_ce0_local;

assign p_ZL16post_spike_times_7_d0 = 32'd0;

assign p_ZL16post_spike_times_7_we0 = p_ZL16post_spike_times_7_we0_local;

assign tmp_fu_312_p3 = ap_sig_allocacmp_i_1[32'd6];

assign zext_ln363_fu_330_p1 = lshr_ln_fu_320_p4;

endmodule //snn_top_hls_snn_top_hls_Pipeline_RESET_PRE
