// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_apply_weight_updates_Pipeline_VITIS_LOOP_167_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln189,
        and_ln177,
        sext_ln184_1,
        sext_ln184,
        weight_update_fifo_dout,
        weight_update_fifo_empty_n,
        weight_update_fifo_read,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_we1,
        p_ZL13weight_memory_0_d1,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_we1,
        p_ZL13weight_memory_1_d1,
        p_ZL13weight_memory_2_address0,
        p_ZL13weight_memory_2_ce0,
        p_ZL13weight_memory_2_q0,
        p_ZL13weight_memory_2_address1,
        p_ZL13weight_memory_2_ce1,
        p_ZL13weight_memory_2_we1,
        p_ZL13weight_memory_2_d1,
        p_ZL13weight_memory_3_address0,
        p_ZL13weight_memory_3_ce0,
        p_ZL13weight_memory_3_q0,
        p_ZL13weight_memory_3_address1,
        p_ZL13weight_memory_3_ce1,
        p_ZL13weight_memory_3_we1,
        p_ZL13weight_memory_3_d1,
        p_ZL13weight_memory_4_address0,
        p_ZL13weight_memory_4_ce0,
        p_ZL13weight_memory_4_q0,
        p_ZL13weight_memory_4_address1,
        p_ZL13weight_memory_4_ce1,
        p_ZL13weight_memory_4_we1,
        p_ZL13weight_memory_4_d1,
        p_ZL13weight_memory_5_address0,
        p_ZL13weight_memory_5_ce0,
        p_ZL13weight_memory_5_q0,
        p_ZL13weight_memory_5_address1,
        p_ZL13weight_memory_5_ce1,
        p_ZL13weight_memory_5_we1,
        p_ZL13weight_memory_5_d1,
        p_ZL13weight_memory_6_address0,
        p_ZL13weight_memory_6_ce0,
        p_ZL13weight_memory_6_q0,
        p_ZL13weight_memory_6_address1,
        p_ZL13weight_memory_6_ce1,
        p_ZL13weight_memory_6_we1,
        p_ZL13weight_memory_6_d1,
        p_ZL13weight_memory_7_address0,
        p_ZL13weight_memory_7_ce0,
        p_ZL13weight_memory_7_q0,
        p_ZL13weight_memory_7_address1,
        p_ZL13weight_memory_7_ce1,
        p_ZL13weight_memory_7_we1,
        p_ZL13weight_memory_7_d1,
        p_ZL18eligibility_traces_0_address0,
        p_ZL18eligibility_traces_0_ce0,
        p_ZL18eligibility_traces_0_q0,
        p_ZL18eligibility_traces_0_address1,
        p_ZL18eligibility_traces_0_ce1,
        p_ZL18eligibility_traces_0_we1,
        p_ZL18eligibility_traces_0_d1,
        p_ZL18eligibility_traces_1_address0,
        p_ZL18eligibility_traces_1_ce0,
        p_ZL18eligibility_traces_1_q0,
        p_ZL18eligibility_traces_1_address1,
        p_ZL18eligibility_traces_1_ce1,
        p_ZL18eligibility_traces_1_we1,
        p_ZL18eligibility_traces_1_d1,
        p_ZL18eligibility_traces_2_address0,
        p_ZL18eligibility_traces_2_ce0,
        p_ZL18eligibility_traces_2_q0,
        p_ZL18eligibility_traces_2_address1,
        p_ZL18eligibility_traces_2_ce1,
        p_ZL18eligibility_traces_2_we1,
        p_ZL18eligibility_traces_2_d1,
        p_ZL18eligibility_traces_3_address0,
        p_ZL18eligibility_traces_3_ce0,
        p_ZL18eligibility_traces_3_q0,
        p_ZL18eligibility_traces_3_address1,
        p_ZL18eligibility_traces_3_ce1,
        p_ZL18eligibility_traces_3_we1,
        p_ZL18eligibility_traces_3_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] sext_ln189;
input  [0:0] and_ln177;
input  [9:0] sext_ln184_1;
input  [15:0] sext_ln184;
input  [63:0] weight_update_fifo_dout;
input   weight_update_fifo_empty_n;
output   weight_update_fifo_read;
output  [8:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [8:0] p_ZL13weight_memory_0_address1;
output   p_ZL13weight_memory_0_ce1;
output   p_ZL13weight_memory_0_we1;
output  [7:0] p_ZL13weight_memory_0_d1;
output  [8:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [8:0] p_ZL13weight_memory_1_address1;
output   p_ZL13weight_memory_1_ce1;
output   p_ZL13weight_memory_1_we1;
output  [7:0] p_ZL13weight_memory_1_d1;
output  [8:0] p_ZL13weight_memory_2_address0;
output   p_ZL13weight_memory_2_ce0;
input  [7:0] p_ZL13weight_memory_2_q0;
output  [8:0] p_ZL13weight_memory_2_address1;
output   p_ZL13weight_memory_2_ce1;
output   p_ZL13weight_memory_2_we1;
output  [7:0] p_ZL13weight_memory_2_d1;
output  [8:0] p_ZL13weight_memory_3_address0;
output   p_ZL13weight_memory_3_ce0;
input  [7:0] p_ZL13weight_memory_3_q0;
output  [8:0] p_ZL13weight_memory_3_address1;
output   p_ZL13weight_memory_3_ce1;
output   p_ZL13weight_memory_3_we1;
output  [7:0] p_ZL13weight_memory_3_d1;
output  [8:0] p_ZL13weight_memory_4_address0;
output   p_ZL13weight_memory_4_ce0;
input  [7:0] p_ZL13weight_memory_4_q0;
output  [8:0] p_ZL13weight_memory_4_address1;
output   p_ZL13weight_memory_4_ce1;
output   p_ZL13weight_memory_4_we1;
output  [7:0] p_ZL13weight_memory_4_d1;
output  [8:0] p_ZL13weight_memory_5_address0;
output   p_ZL13weight_memory_5_ce0;
input  [7:0] p_ZL13weight_memory_5_q0;
output  [8:0] p_ZL13weight_memory_5_address1;
output   p_ZL13weight_memory_5_ce1;
output   p_ZL13weight_memory_5_we1;
output  [7:0] p_ZL13weight_memory_5_d1;
output  [8:0] p_ZL13weight_memory_6_address0;
output   p_ZL13weight_memory_6_ce0;
input  [7:0] p_ZL13weight_memory_6_q0;
output  [8:0] p_ZL13weight_memory_6_address1;
output   p_ZL13weight_memory_6_ce1;
output   p_ZL13weight_memory_6_we1;
output  [7:0] p_ZL13weight_memory_6_d1;
output  [8:0] p_ZL13weight_memory_7_address0;
output   p_ZL13weight_memory_7_ce0;
input  [7:0] p_ZL13weight_memory_7_q0;
output  [8:0] p_ZL13weight_memory_7_address1;
output   p_ZL13weight_memory_7_ce1;
output   p_ZL13weight_memory_7_we1;
output  [7:0] p_ZL13weight_memory_7_d1;
output  [9:0] p_ZL18eligibility_traces_0_address0;
output   p_ZL18eligibility_traces_0_ce0;
input  [15:0] p_ZL18eligibility_traces_0_q0;
output  [9:0] p_ZL18eligibility_traces_0_address1;
output   p_ZL18eligibility_traces_0_ce1;
output   p_ZL18eligibility_traces_0_we1;
output  [15:0] p_ZL18eligibility_traces_0_d1;
output  [9:0] p_ZL18eligibility_traces_1_address0;
output   p_ZL18eligibility_traces_1_ce0;
input  [15:0] p_ZL18eligibility_traces_1_q0;
output  [9:0] p_ZL18eligibility_traces_1_address1;
output   p_ZL18eligibility_traces_1_ce1;
output   p_ZL18eligibility_traces_1_we1;
output  [15:0] p_ZL18eligibility_traces_1_d1;
output  [9:0] p_ZL18eligibility_traces_2_address0;
output   p_ZL18eligibility_traces_2_ce0;
input  [15:0] p_ZL18eligibility_traces_2_q0;
output  [9:0] p_ZL18eligibility_traces_2_address1;
output   p_ZL18eligibility_traces_2_ce1;
output   p_ZL18eligibility_traces_2_we1;
output  [15:0] p_ZL18eligibility_traces_2_d1;
output  [9:0] p_ZL18eligibility_traces_3_address0;
output   p_ZL18eligibility_traces_3_ce0;
input  [15:0] p_ZL18eligibility_traces_3_q0;
output  [9:0] p_ZL18eligibility_traces_3_address1;
output   p_ZL18eligibility_traces_3_ce1;
output   p_ZL18eligibility_traces_3_we1;
output  [15:0] p_ZL18eligibility_traces_3_d1;

reg ap_idle;
reg weight_update_fifo_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] tmp_reg_899;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    weight_update_fifo_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg  signed [15:0] modulated_delta_2_reg_424;
wire   [0:0] and_ln177_read_reg_880;
wire    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln184_cast_fu_434_p1;
reg  signed [31:0] sext_ln184_cast_reg_884;
wire  signed [31:0] sext_ln189_cast_fu_438_p1;
reg  signed [31:0] sext_ln189_cast_reg_889;
wire  signed [25:0] sext_ln184_1_cast_fu_442_p1;
reg  signed [25:0] sext_ln184_1_cast_reg_894;
wire   [0:0] tmp_nbreadreq_fu_202_p3;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [5:0] trunc_ln173_fu_454_p1;
reg   [5:0] trunc_ln173_reg_908;
reg   [2:0] update_post_id_cast_reg_914;
reg   [2:0] update_post_id_cast_reg_914_pp0_iter1_reg;
reg   [1:0] update_post_id_cast2_reg_920;
reg   [5:0] lshr_ln3_reg_927;
reg   [4:0] lshr_ln173_s_reg_932;
wire  signed [15:0] shl_ln_fu_508_p3;
reg  signed [15:0] shl_ln_reg_937;
reg   [9:0] p_ZL18eligibility_traces_0_addr_reg_947;
wire    ap_block_pp0_stage2_11001;
reg   [9:0] p_ZL18eligibility_traces_1_addr_reg_953;
reg   [9:0] p_ZL18eligibility_traces_2_addr_reg_959;
reg   [9:0] p_ZL18eligibility_traces_3_addr_reg_965;
wire   [8:0] add_ln173_fu_554_p2;
reg   [8:0] add_ln173_reg_971;
wire  signed [25:0] mul_ln180_fu_563_p2;
reg  signed [25:0] mul_ln180_reg_976;
reg   [7:0] tmp_25_cast_reg_981;
wire   [15:0] trunc_ln180_fu_578_p1;
reg   [15:0] trunc_ln180_reg_988;
reg   [8:0] p_ZL13weight_memory_0_addr_reg_993;
wire    ap_block_pp0_stage3_11001;
reg   [8:0] p_ZL13weight_memory_1_addr_reg_999;
reg   [8:0] p_ZL13weight_memory_2_addr_reg_1005;
reg   [8:0] p_ZL13weight_memory_3_addr_reg_1011;
reg   [8:0] p_ZL13weight_memory_4_addr_reg_1017;
reg   [8:0] p_ZL13weight_memory_5_addr_reg_1023;
reg   [8:0] p_ZL13weight_memory_6_addr_reg_1029;
reg   [8:0] p_ZL13weight_memory_7_addr_reg_1035;
wire   [7:0] current_weight_fu_685_p19;
reg   [7:0] current_weight_reg_1046;
reg   [15:0] trunc_ln4_reg_1054;
wire   [31:0] mul_ln189_fu_760_p2;
reg   [31:0] mul_ln189_reg_1062;
reg   [15:0] tmp_118_cast_reg_1067;
wire   [7:0] trunc_ln189_fu_775_p1;
reg   [7:0] trunc_ln189_reg_1074;
wire   [15:0] new_weight_fu_813_p2;
reg   [15:0] new_weight_reg_1079;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln70_fu_829_p2;
reg   [0:0] icmp_ln70_reg_1085;
wire  signed [15:0] sext_ln176_fu_628_p1;
reg   [15:0] ap_phi_reg_pp0_iter0_modulated_delta_2_reg_424;
wire   [63:0] zext_ln183_1_fu_543_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln173_1_fu_582_p1;
wire    ap_block_pp0_stage3;
reg    p_ZL18eligibility_traces_0_ce0_local;
reg    p_ZL18eligibility_traces_0_we1_local;
wire   [0:0] icmp_ln183_fu_724_p2;
reg   [15:0] p_ZL18eligibility_traces_0_d1_local;
wire    ap_block_pp0_stage0;
reg    p_ZL18eligibility_traces_0_ce1_local;
wire    ap_block_pp0_stage1_grp0;
reg    p_ZL18eligibility_traces_1_ce0_local;
reg    p_ZL18eligibility_traces_1_we1_local;
reg   [15:0] p_ZL18eligibility_traces_1_d1_local;
reg    p_ZL18eligibility_traces_1_ce1_local;
reg    p_ZL18eligibility_traces_2_ce0_local;
reg    p_ZL18eligibility_traces_2_we1_local;
reg   [15:0] p_ZL18eligibility_traces_2_d1_local;
reg    p_ZL18eligibility_traces_2_ce1_local;
reg    p_ZL18eligibility_traces_3_ce0_local;
reg    p_ZL18eligibility_traces_3_we1_local;
reg   [15:0] p_ZL18eligibility_traces_3_d1_local;
reg    p_ZL18eligibility_traces_3_ce1_local;
reg    p_ZL13weight_memory_0_ce0_local;
reg    p_ZL13weight_memory_0_we1_local;
wire   [7:0] select_ln70_fu_855_p3;
reg    p_ZL13weight_memory_0_ce1_local;
reg    p_ZL13weight_memory_1_ce0_local;
reg    p_ZL13weight_memory_1_we1_local;
reg    p_ZL13weight_memory_1_ce1_local;
reg    p_ZL13weight_memory_2_ce0_local;
reg    p_ZL13weight_memory_2_we1_local;
reg    p_ZL13weight_memory_2_ce1_local;
reg    p_ZL13weight_memory_3_ce0_local;
reg    p_ZL13weight_memory_3_we1_local;
reg    p_ZL13weight_memory_3_ce1_local;
reg    p_ZL13weight_memory_4_ce0_local;
reg    p_ZL13weight_memory_4_we1_local;
reg    p_ZL13weight_memory_4_ce1_local;
reg    p_ZL13weight_memory_5_ce0_local;
reg    p_ZL13weight_memory_5_we1_local;
reg    p_ZL13weight_memory_5_ce1_local;
reg    p_ZL13weight_memory_6_ce0_local;
reg    p_ZL13weight_memory_6_we1_local;
reg    p_ZL13weight_memory_6_ce1_local;
reg    p_ZL13weight_memory_7_ce0_local;
reg    p_ZL13weight_memory_7_we1_local;
reg    p_ZL13weight_memory_7_ce1_local;
wire   [7:0] tmp_111_fu_498_p4;
wire   [9:0] tmp_110_fu_527_p3;
wire   [9:0] zext_ln183_fu_534_p1;
wire   [9:0] add_ln183_1_fu_537_p2;
wire   [8:0] tmp_s_fu_520_p3;
wire   [8:0] zext_ln173_fu_551_p1;
wire  signed [9:0] mul_ln180_fu_563_p1;
wire  signed [26:0] sext_ln180_2_fu_593_p1;
wire   [0:0] icmp_ln180_fu_604_p2;
wire   [7:0] add_ln180_fu_609_p2;
wire   [0:0] tmp_108_fu_596_p3;
wire   [7:0] select_ln180_fu_614_p3;
wire   [7:0] modulated_delta_1_fu_621_p3;
wire   [15:0] tmp_112_fu_633_p9;
wire   [15:0] tmp_112_fu_633_p11;
wire  signed [23:0] shl_ln3_fu_656_p3;
wire   [7:0] current_weight_fu_685_p17;
wire  signed [31:0] grp_fu_871_p3;
wire  signed [15:0] mul_ln189_fu_760_p1;
wire   [0:0] icmp_ln189_fu_789_p2;
wire   [15:0] add_ln189_fu_794_p2;
wire   [0:0] tmp_109_fu_782_p3;
wire   [15:0] select_ln189_fu_799_p3;
wire   [15:0] select_ln189_1_fu_806_p3;
wire  signed [15:0] sext_ln188_fu_779_p1;
wire   [8:0] tmp_113_fu_819_p4;
wire   [0:0] icmp_ln71_fu_835_p2;
wire   [0:0] or_ln70_fu_850_p2;
wire   [7:0] select_ln70_1_fu_843_p3;
wire   [7:0] trunc_ln72_fu_840_p1;
wire  signed [15:0] grp_fu_871_p1;
reg    grp_fu_871_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_loop_init;
reg    ap_condition_328;
wire   [1:0] tmp_112_fu_633_p1;
wire   [1:0] tmp_112_fu_633_p3;
wire  signed [1:0] tmp_112_fu_633_p5;
wire  signed [1:0] tmp_112_fu_633_p7;
wire   [2:0] current_weight_fu_685_p1;
wire   [2:0] current_weight_fu_685_p3;
wire   [2:0] current_weight_fu_685_p5;
wire   [2:0] current_weight_fu_685_p7;
wire  signed [2:0] current_weight_fu_685_p9;
wire  signed [2:0] current_weight_fu_685_p11;
wire  signed [2:0] current_weight_fu_685_p13;
wire  signed [2:0] current_weight_fu_685_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U178(
    .din0(shl_ln_reg_937),
    .din1(mul_ln180_fu_563_p1),
    .dout(mul_ln180_fu_563_p2)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U179(
    .din0(p_ZL18eligibility_traces_0_q0),
    .din1(p_ZL18eligibility_traces_1_q0),
    .din2(p_ZL18eligibility_traces_2_q0),
    .din3(p_ZL18eligibility_traces_3_q0),
    .def(tmp_112_fu_633_p9),
    .sel(update_post_id_cast2_reg_920),
    .dout(tmp_112_fu_633_p11)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U180(
    .din0(p_ZL13weight_memory_0_q0),
    .din1(p_ZL13weight_memory_1_q0),
    .din2(p_ZL13weight_memory_2_q0),
    .din3(p_ZL13weight_memory_3_q0),
    .din4(p_ZL13weight_memory_4_q0),
    .din5(p_ZL13weight_memory_5_q0),
    .din6(p_ZL13weight_memory_6_q0),
    .din7(p_ZL13weight_memory_7_q0),
    .def(current_weight_fu_685_p17),
    .sel(update_post_id_cast_reg_914),
    .dout(current_weight_fu_685_p19)
);

snn_top_hls_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U181(
    .din0(modulated_delta_2_reg_424),
    .din1(mul_ln189_fu_760_p1),
    .dout(mul_ln189_fu_760_p2)
);

snn_top_hls_mac_muladd_16s_16s_24s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_24s_32_4_1_U182(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shl_ln_fu_508_p3),
    .din1(grp_fu_871_p1),
    .din2(shl_ln3_fu_656_p3),
    .ce(grp_fu_871_ce),
    .dout(grp_fu_871_p3)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_328)) begin
        if (((tmp_reg_899 == 1'd1) & (1'd1 == and_ln177))) begin
            modulated_delta_2_reg_424 <= sext_ln176_fu_628_p1;
        end else if ((1'b1 == 1'b1)) begin
            modulated_delta_2_reg_424 <= ap_phi_reg_pp0_iter0_modulated_delta_2_reg_424;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln173_reg_971 <= add_ln173_fu_554_p2;
        mul_ln180_reg_976 <= mul_ln180_fu_563_p2;
        p_ZL18eligibility_traces_0_addr_reg_947 <= zext_ln183_1_fu_543_p1;
        p_ZL18eligibility_traces_1_addr_reg_953 <= zext_ln183_1_fu_543_p1;
        p_ZL18eligibility_traces_2_addr_reg_959 <= zext_ln183_1_fu_543_p1;
        p_ZL18eligibility_traces_3_addr_reg_965 <= zext_ln183_1_fu_543_p1;
        tmp_25_cast_reg_981 <= {{mul_ln180_fu_563_p2[23:16]}};
        trunc_ln180_reg_988 <= trunc_ln180_fu_578_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln177_read_reg_880) & (tmp_reg_899 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter0_modulated_delta_2_reg_424 <= {{weight_update_fifo_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_weight_reg_1046 <= current_weight_fu_685_p19;
        mul_ln189_reg_1062 <= mul_ln189_fu_760_p2;
        sext_ln184_1_cast_reg_894 <= sext_ln184_1_cast_fu_442_p1;
        sext_ln184_cast_reg_884 <= sext_ln184_cast_fu_434_p1;
        sext_ln189_cast_reg_889 <= sext_ln189_cast_fu_438_p1;
        tmp_118_cast_reg_1067 <= {{mul_ln189_fu_760_p2[23:8]}};
        tmp_reg_899 <= tmp_nbreadreq_fu_202_p3;
        trunc_ln189_reg_1074 <= trunc_ln189_fu_775_p1;
        trunc_ln4_reg_1054 <= {{grp_fu_871_p3[23:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln70_reg_1085 <= icmp_ln70_fu_829_p2;
        new_weight_reg_1079 <= new_weight_fu_813_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lshr_ln173_s_reg_932 <= {{weight_update_fifo_dout[15:11]}};
        lshr_ln3_reg_927 <= {{weight_update_fifo_dout[15:10]}};
        shl_ln_reg_937[15 : 8] <= shl_ln_fu_508_p3[15 : 8];
        trunc_ln173_reg_908 <= trunc_ln173_fu_454_p1;
        update_post_id_cast2_reg_920 <= {{weight_update_fifo_dout[9:8]}};
        update_post_id_cast_reg_914 <= {{weight_update_fifo_dout[10:8]}};
        update_post_id_cast_reg_914_pp0_iter1_reg <= update_post_id_cast_reg_914;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_0_addr_reg_993 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_1_addr_reg_999 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_2_addr_reg_1005 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_3_addr_reg_1011 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_4_addr_reg_1017 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_5_addr_reg_1023 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_6_addr_reg_1029 <= zext_ln173_1_fu_582_p1;
        p_ZL13weight_memory_7_addr_reg_1035 <= zext_ln173_1_fu_582_p1;
    end
end

always @ (*) begin
    if (((tmp_reg_899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_871_ce = 1'b1;
    end else begin
        grp_fu_871_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_0_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_0_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_1_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_1_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_2_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_2_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_2_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_3_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_3_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_3_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_4_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_4_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd4) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_4_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_5_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_5_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd5) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_5_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_6_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_6_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd6) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_6_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_ZL13weight_memory_7_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_7_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast_reg_914_pp0_iter1_reg == 3'd7) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL13weight_memory_7_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL18eligibility_traces_0_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_0_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_0_d1_local = trunc_ln4_reg_1054;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_0_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_0_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_0_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd0) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln183_fu_724_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd0) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_0_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL18eligibility_traces_1_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_1_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_1_d1_local = trunc_ln4_reg_1054;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_1_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_1_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_1_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd1) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln183_fu_724_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd1) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_1_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL18eligibility_traces_2_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_2_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_2_d1_local = trunc_ln4_reg_1054;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_2_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_2_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_2_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd2) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln183_fu_724_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd2) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_2_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_ZL18eligibility_traces_3_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_3_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_3_d1_local = trunc_ln4_reg_1054;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_3_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_3_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_3_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd3) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln183_fu_724_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (update_post_id_cast2_reg_920 == 2'd3) & (1'd1 == and_ln177) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL18eligibility_traces_3_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_899 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_update_fifo_blk_n = weight_update_fifo_empty_n;
    end else begin
        weight_update_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_reg_899 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_update_fifo_read = 1'b1;
    end else begin
        weight_update_fifo_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln173_fu_554_p2 = (tmp_s_fu_520_p3 + zext_ln173_fu_551_p1);

assign add_ln180_fu_609_p2 = (tmp_25_cast_reg_981 + 8'd1);

assign add_ln183_1_fu_537_p2 = (tmp_110_fu_527_p3 + zext_ln183_fu_534_p1);

assign add_ln189_fu_794_p2 = (tmp_118_cast_reg_1067 + 16'd1);

assign and_ln177_read_reg_880 = and_ln177;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((weight_update_fifo_empty_n == 1'b0) & (tmp_reg_899 == 1'd1));
end

always @ (*) begin
    ap_condition_328 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign current_weight_fu_685_p17 = 'bx;

assign grp_fu_871_p1 = sext_ln184_cast_reg_884;

assign icmp_ln180_fu_604_p2 = ((trunc_ln180_reg_988 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_724_p2 = ((grp_fu_871_p3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_789_p2 = ((trunc_ln189_reg_1074 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_829_p2 = (($signed(tmp_113_fu_819_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_835_p2 = (($signed(new_weight_reg_1079) < $signed(16'd65408)) ? 1'b1 : 1'b0);

assign modulated_delta_1_fu_621_p3 = ((tmp_108_fu_596_p3[0:0] == 1'b1) ? select_ln180_fu_614_p3 : tmp_25_cast_reg_981);

assign mul_ln180_fu_563_p1 = sext_ln184_1_cast_reg_894;

assign mul_ln189_fu_760_p1 = sext_ln189_cast_reg_889;

assign new_weight_fu_813_p2 = ($signed(select_ln189_1_fu_806_p3) + $signed(sext_ln188_fu_779_p1));

assign or_ln70_fu_850_p2 = (icmp_ln71_fu_835_p2 | icmp_ln70_reg_1085);

assign p_ZL13weight_memory_0_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_0_address1 = p_ZL13weight_memory_0_addr_reg_993;

assign p_ZL13weight_memory_0_ce0 = p_ZL13weight_memory_0_ce0_local;

assign p_ZL13weight_memory_0_ce1 = p_ZL13weight_memory_0_ce1_local;

assign p_ZL13weight_memory_0_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_0_we1 = p_ZL13weight_memory_0_we1_local;

assign p_ZL13weight_memory_1_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_1_address1 = p_ZL13weight_memory_1_addr_reg_999;

assign p_ZL13weight_memory_1_ce0 = p_ZL13weight_memory_1_ce0_local;

assign p_ZL13weight_memory_1_ce1 = p_ZL13weight_memory_1_ce1_local;

assign p_ZL13weight_memory_1_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_1_we1 = p_ZL13weight_memory_1_we1_local;

assign p_ZL13weight_memory_2_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_2_address1 = p_ZL13weight_memory_2_addr_reg_1005;

assign p_ZL13weight_memory_2_ce0 = p_ZL13weight_memory_2_ce0_local;

assign p_ZL13weight_memory_2_ce1 = p_ZL13weight_memory_2_ce1_local;

assign p_ZL13weight_memory_2_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_2_we1 = p_ZL13weight_memory_2_we1_local;

assign p_ZL13weight_memory_3_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_3_address1 = p_ZL13weight_memory_3_addr_reg_1011;

assign p_ZL13weight_memory_3_ce0 = p_ZL13weight_memory_3_ce0_local;

assign p_ZL13weight_memory_3_ce1 = p_ZL13weight_memory_3_ce1_local;

assign p_ZL13weight_memory_3_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_3_we1 = p_ZL13weight_memory_3_we1_local;

assign p_ZL13weight_memory_4_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_4_address1 = p_ZL13weight_memory_4_addr_reg_1017;

assign p_ZL13weight_memory_4_ce0 = p_ZL13weight_memory_4_ce0_local;

assign p_ZL13weight_memory_4_ce1 = p_ZL13weight_memory_4_ce1_local;

assign p_ZL13weight_memory_4_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_4_we1 = p_ZL13weight_memory_4_we1_local;

assign p_ZL13weight_memory_5_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_5_address1 = p_ZL13weight_memory_5_addr_reg_1023;

assign p_ZL13weight_memory_5_ce0 = p_ZL13weight_memory_5_ce0_local;

assign p_ZL13weight_memory_5_ce1 = p_ZL13weight_memory_5_ce1_local;

assign p_ZL13weight_memory_5_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_5_we1 = p_ZL13weight_memory_5_we1_local;

assign p_ZL13weight_memory_6_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_6_address1 = p_ZL13weight_memory_6_addr_reg_1029;

assign p_ZL13weight_memory_6_ce0 = p_ZL13weight_memory_6_ce0_local;

assign p_ZL13weight_memory_6_ce1 = p_ZL13weight_memory_6_ce1_local;

assign p_ZL13weight_memory_6_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_6_we1 = p_ZL13weight_memory_6_we1_local;

assign p_ZL13weight_memory_7_address0 = zext_ln173_1_fu_582_p1;

assign p_ZL13weight_memory_7_address1 = p_ZL13weight_memory_7_addr_reg_1035;

assign p_ZL13weight_memory_7_ce0 = p_ZL13weight_memory_7_ce0_local;

assign p_ZL13weight_memory_7_ce1 = p_ZL13weight_memory_7_ce1_local;

assign p_ZL13weight_memory_7_d1 = select_ln70_fu_855_p3;

assign p_ZL13weight_memory_7_we1 = p_ZL13weight_memory_7_we1_local;

assign p_ZL18eligibility_traces_0_address0 = zext_ln183_1_fu_543_p1;

assign p_ZL18eligibility_traces_0_address1 = p_ZL18eligibility_traces_0_addr_reg_947;

assign p_ZL18eligibility_traces_0_ce0 = p_ZL18eligibility_traces_0_ce0_local;

assign p_ZL18eligibility_traces_0_ce1 = p_ZL18eligibility_traces_0_ce1_local;

assign p_ZL18eligibility_traces_0_d1 = p_ZL18eligibility_traces_0_d1_local;

assign p_ZL18eligibility_traces_0_we1 = p_ZL18eligibility_traces_0_we1_local;

assign p_ZL18eligibility_traces_1_address0 = zext_ln183_1_fu_543_p1;

assign p_ZL18eligibility_traces_1_address1 = p_ZL18eligibility_traces_1_addr_reg_953;

assign p_ZL18eligibility_traces_1_ce0 = p_ZL18eligibility_traces_1_ce0_local;

assign p_ZL18eligibility_traces_1_ce1 = p_ZL18eligibility_traces_1_ce1_local;

assign p_ZL18eligibility_traces_1_d1 = p_ZL18eligibility_traces_1_d1_local;

assign p_ZL18eligibility_traces_1_we1 = p_ZL18eligibility_traces_1_we1_local;

assign p_ZL18eligibility_traces_2_address0 = zext_ln183_1_fu_543_p1;

assign p_ZL18eligibility_traces_2_address1 = p_ZL18eligibility_traces_2_addr_reg_959;

assign p_ZL18eligibility_traces_2_ce0 = p_ZL18eligibility_traces_2_ce0_local;

assign p_ZL18eligibility_traces_2_ce1 = p_ZL18eligibility_traces_2_ce1_local;

assign p_ZL18eligibility_traces_2_d1 = p_ZL18eligibility_traces_2_d1_local;

assign p_ZL18eligibility_traces_2_we1 = p_ZL18eligibility_traces_2_we1_local;

assign p_ZL18eligibility_traces_3_address0 = zext_ln183_1_fu_543_p1;

assign p_ZL18eligibility_traces_3_address1 = p_ZL18eligibility_traces_3_addr_reg_965;

assign p_ZL18eligibility_traces_3_ce0 = p_ZL18eligibility_traces_3_ce0_local;

assign p_ZL18eligibility_traces_3_ce1 = p_ZL18eligibility_traces_3_ce1_local;

assign p_ZL18eligibility_traces_3_d1 = p_ZL18eligibility_traces_3_d1_local;

assign p_ZL18eligibility_traces_3_we1 = p_ZL18eligibility_traces_3_we1_local;

assign select_ln180_fu_614_p3 = ((icmp_ln180_fu_604_p2[0:0] == 1'b1) ? add_ln180_fu_609_p2 : tmp_25_cast_reg_981);

assign select_ln189_1_fu_806_p3 = ((tmp_109_fu_782_p3[0:0] == 1'b1) ? select_ln189_fu_799_p3 : tmp_118_cast_reg_1067);

assign select_ln189_fu_799_p3 = ((icmp_ln189_fu_789_p2[0:0] == 1'b1) ? add_ln189_fu_794_p2 : tmp_118_cast_reg_1067);

assign select_ln70_1_fu_843_p3 = ((icmp_ln70_reg_1085[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln70_fu_855_p3 = ((or_ln70_fu_850_p2[0:0] == 1'b1) ? select_ln70_1_fu_843_p3 : trunc_ln72_fu_840_p1);

assign sext_ln176_fu_628_p1 = $signed(modulated_delta_1_fu_621_p3);

assign sext_ln180_2_fu_593_p1 = mul_ln180_reg_976;

assign sext_ln184_1_cast_fu_442_p1 = $signed(sext_ln184_1);

assign sext_ln184_cast_fu_434_p1 = $signed(sext_ln184);

assign sext_ln188_fu_779_p1 = $signed(current_weight_reg_1046);

assign sext_ln189_cast_fu_438_p1 = $signed(sext_ln189);

assign shl_ln3_fu_656_p3 = {{tmp_112_fu_633_p11}, {8'd0}};

assign shl_ln_fu_508_p3 = {{tmp_111_fu_498_p4}, {8'd0}};

assign tmp_108_fu_596_p3 = sext_ln180_2_fu_593_p1[32'd26];

assign tmp_109_fu_782_p3 = mul_ln189_reg_1062[32'd31];

assign tmp_110_fu_527_p3 = {{trunc_ln173_reg_908}, {4'd0}};

assign tmp_111_fu_498_p4 = {{weight_update_fifo_dout[23:16]}};

assign tmp_112_fu_633_p9 = 'bx;

assign tmp_113_fu_819_p4 = {{new_weight_fu_813_p2[15:7]}};

assign tmp_nbreadreq_fu_202_p3 = weight_update_fifo_empty_n;

assign tmp_s_fu_520_p3 = {{trunc_ln173_reg_908}, {3'd0}};

assign trunc_ln173_fu_454_p1 = weight_update_fifo_dout[5:0];

assign trunc_ln180_fu_578_p1 = mul_ln180_fu_563_p2[15:0];

assign trunc_ln189_fu_775_p1 = mul_ln189_fu_760_p2[7:0];

assign trunc_ln72_fu_840_p1 = new_weight_reg_1079[7:0];

assign zext_ln173_1_fu_582_p1 = add_ln173_reg_971;

assign zext_ln173_fu_551_p1 = lshr_ln173_s_reg_932;

assign zext_ln183_1_fu_543_p1 = add_ln183_1_fu_537_p2;

assign zext_ln183_fu_534_p1 = lshr_ln3_reg_927;

always @ (posedge ap_clk) begin
    shl_ln_reg_937[7:0] <= 8'b00000000;
end

endmodule //snn_top_hls_apply_weight_updates_Pipeline_VITIS_LOOP_167_1
