// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_process_pre_spike (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pre_id,
        current_time,
        params_a_plus_val,
        params_a_minus_val,
        params_tau_plus_val,
        params_tau_minus_val,
        params_stdp_window_val,
        p_ZL15pre_spike_times_0_address0,
        p_ZL15pre_spike_times_0_ce0,
        p_ZL15pre_spike_times_0_we0,
        p_ZL15pre_spike_times_0_d0,
        p_ZL15pre_spike_times_1_address0,
        p_ZL15pre_spike_times_1_ce0,
        p_ZL15pre_spike_times_1_we0,
        p_ZL15pre_spike_times_1_d0,
        p_ZL15pre_spike_times_2_address0,
        p_ZL15pre_spike_times_2_ce0,
        p_ZL15pre_spike_times_2_we0,
        p_ZL15pre_spike_times_2_d0,
        p_ZL15pre_spike_times_3_address0,
        p_ZL15pre_spike_times_3_ce0,
        p_ZL15pre_spike_times_3_we0,
        p_ZL15pre_spike_times_3_d0,
        p_ZL15pre_spike_times_4_address0,
        p_ZL15pre_spike_times_4_ce0,
        p_ZL15pre_spike_times_4_we0,
        p_ZL15pre_spike_times_4_d0,
        p_ZL15pre_spike_times_5_address0,
        p_ZL15pre_spike_times_5_ce0,
        p_ZL15pre_spike_times_5_we0,
        p_ZL15pre_spike_times_5_d0,
        p_ZL15pre_spike_times_6_address0,
        p_ZL15pre_spike_times_6_ce0,
        p_ZL15pre_spike_times_6_we0,
        p_ZL15pre_spike_times_6_d0,
        p_ZL15pre_spike_times_7_address0,
        p_ZL15pre_spike_times_7_ce0,
        p_ZL15pre_spike_times_7_we0,
        p_ZL15pre_spike_times_7_d0,
        p_ZL16post_spike_times_7_address0,
        p_ZL16post_spike_times_7_ce0,
        p_ZL16post_spike_times_7_q0,
        p_ZL16post_spike_times_6_address0,
        p_ZL16post_spike_times_6_ce0,
        p_ZL16post_spike_times_6_q0,
        p_ZL16post_spike_times_5_address0,
        p_ZL16post_spike_times_5_ce0,
        p_ZL16post_spike_times_5_q0,
        p_ZL16post_spike_times_4_address0,
        p_ZL16post_spike_times_4_ce0,
        p_ZL16post_spike_times_4_q0,
        p_ZL16post_spike_times_3_address0,
        p_ZL16post_spike_times_3_ce0,
        p_ZL16post_spike_times_3_q0,
        p_ZL16post_spike_times_2_address0,
        p_ZL16post_spike_times_2_ce0,
        p_ZL16post_spike_times_2_q0,
        p_ZL16post_spike_times_1_address0,
        p_ZL16post_spike_times_1_ce0,
        p_ZL16post_spike_times_1_q0,
        p_ZL16post_spike_times_0_address0,
        p_ZL16post_spike_times_0_ce0,
        p_ZL16post_spike_times_0_q0,
        weight_update_fifo_din,
        weight_update_fifo_full_n,
        weight_update_fifo_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] pre_id;
input  [31:0] current_time;
input  [15:0] params_a_plus_val;
input  [15:0] params_a_minus_val;
input  [7:0] params_tau_plus_val;
input  [7:0] params_tau_minus_val;
input  [15:0] params_stdp_window_val;
output  [2:0] p_ZL15pre_spike_times_0_address0;
output   p_ZL15pre_spike_times_0_ce0;
output   p_ZL15pre_spike_times_0_we0;
output  [31:0] p_ZL15pre_spike_times_0_d0;
output  [2:0] p_ZL15pre_spike_times_1_address0;
output   p_ZL15pre_spike_times_1_ce0;
output   p_ZL15pre_spike_times_1_we0;
output  [31:0] p_ZL15pre_spike_times_1_d0;
output  [2:0] p_ZL15pre_spike_times_2_address0;
output   p_ZL15pre_spike_times_2_ce0;
output   p_ZL15pre_spike_times_2_we0;
output  [31:0] p_ZL15pre_spike_times_2_d0;
output  [2:0] p_ZL15pre_spike_times_3_address0;
output   p_ZL15pre_spike_times_3_ce0;
output   p_ZL15pre_spike_times_3_we0;
output  [31:0] p_ZL15pre_spike_times_3_d0;
output  [2:0] p_ZL15pre_spike_times_4_address0;
output   p_ZL15pre_spike_times_4_ce0;
output   p_ZL15pre_spike_times_4_we0;
output  [31:0] p_ZL15pre_spike_times_4_d0;
output  [2:0] p_ZL15pre_spike_times_5_address0;
output   p_ZL15pre_spike_times_5_ce0;
output   p_ZL15pre_spike_times_5_we0;
output  [31:0] p_ZL15pre_spike_times_5_d0;
output  [2:0] p_ZL15pre_spike_times_6_address0;
output   p_ZL15pre_spike_times_6_ce0;
output   p_ZL15pre_spike_times_6_we0;
output  [31:0] p_ZL15pre_spike_times_6_d0;
output  [2:0] p_ZL15pre_spike_times_7_address0;
output   p_ZL15pre_spike_times_7_ce0;
output   p_ZL15pre_spike_times_7_we0;
output  [31:0] p_ZL15pre_spike_times_7_d0;
output  [2:0] p_ZL16post_spike_times_7_address0;
output   p_ZL16post_spike_times_7_ce0;
input  [31:0] p_ZL16post_spike_times_7_q0;
output  [2:0] p_ZL16post_spike_times_6_address0;
output   p_ZL16post_spike_times_6_ce0;
input  [31:0] p_ZL16post_spike_times_6_q0;
output  [2:0] p_ZL16post_spike_times_5_address0;
output   p_ZL16post_spike_times_5_ce0;
input  [31:0] p_ZL16post_spike_times_5_q0;
output  [2:0] p_ZL16post_spike_times_4_address0;
output   p_ZL16post_spike_times_4_ce0;
input  [31:0] p_ZL16post_spike_times_4_q0;
output  [2:0] p_ZL16post_spike_times_3_address0;
output   p_ZL16post_spike_times_3_ce0;
input  [31:0] p_ZL16post_spike_times_3_q0;
output  [2:0] p_ZL16post_spike_times_2_address0;
output   p_ZL16post_spike_times_2_ce0;
input  [31:0] p_ZL16post_spike_times_2_q0;
output  [2:0] p_ZL16post_spike_times_1_address0;
output   p_ZL16post_spike_times_1_ce0;
input  [31:0] p_ZL16post_spike_times_1_q0;
output  [2:0] p_ZL16post_spike_times_0_address0;
output   p_ZL16post_spike_times_0_ce0;
input  [31:0] p_ZL16post_spike_times_0_q0;
output  [63:0] weight_update_fifo_din;
input   weight_update_fifo_full_n;
output   weight_update_fifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] shl_ln_fu_336_p3;
reg   [15:0] shl_ln_reg_383;
wire   [15:0] shl_ln1_fu_345_p3;
reg   [15:0] shl_ln1_reg_388;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_done;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_idle;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_ready;
wire   [63:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_weight_update_fifo_din;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_weight_update_fifo_write;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_7_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_7_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_6_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_6_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_5_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_5_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_4_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_4_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_3_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_3_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_2_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_2_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_1_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_1_ce0;
wire   [2:0] grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_0_address0;
wire    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_0_ce0;
reg    grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln88_fu_306_p1;
reg    p_ZL15pre_spike_times_6_we0_local;
wire   [2:0] trunc_ln88_fu_292_p1;
reg    p_ZL15pre_spike_times_6_ce0_local;
reg    p_ZL15pre_spike_times_5_we0_local;
reg    p_ZL15pre_spike_times_5_ce0_local;
reg    p_ZL15pre_spike_times_4_we0_local;
reg    p_ZL15pre_spike_times_4_ce0_local;
reg    p_ZL15pre_spike_times_3_we0_local;
reg    p_ZL15pre_spike_times_3_ce0_local;
reg    p_ZL15pre_spike_times_2_we0_local;
reg    p_ZL15pre_spike_times_2_ce0_local;
reg    p_ZL15pre_spike_times_1_we0_local;
reg    p_ZL15pre_spike_times_1_ce0_local;
reg    p_ZL15pre_spike_times_0_we0_local;
reg    p_ZL15pre_spike_times_0_ce0_local;
reg    p_ZL15pre_spike_times_7_we0_local;
reg    p_ZL15pre_spike_times_7_ce0_local;
wire   [2:0] lshr_ln_fu_296_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start_reg = 1'b0;
end

snn_top_hls_process_pre_spike_Pipeline_STDP_LTD_LOOP grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start),
    .ap_done(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_done),
    .ap_idle(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_idle),
    .ap_ready(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_ready),
    .weight_update_fifo_din(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_weight_update_fifo_din),
    .weight_update_fifo_full_n(weight_update_fifo_full_n),
    .weight_update_fifo_write(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_weight_update_fifo_write),
    .params_stdp_window_val(params_stdp_window_val),
    .current_time(current_time),
    .sext_ln55(shl_ln_reg_383),
    .zext_ln46(params_stdp_window_val),
    .sext_ln48(params_a_plus_val),
    .sext_ln58(shl_ln1_reg_388),
    .sext_ln93(params_a_minus_val),
    .pre_id(pre_id),
    .p_ZL16post_spike_times_7_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_7_address0),
    .p_ZL16post_spike_times_7_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_7_ce0),
    .p_ZL16post_spike_times_7_q0(p_ZL16post_spike_times_7_q0),
    .p_ZL16post_spike_times_6_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_6_address0),
    .p_ZL16post_spike_times_6_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_6_ce0),
    .p_ZL16post_spike_times_6_q0(p_ZL16post_spike_times_6_q0),
    .p_ZL16post_spike_times_5_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_5_address0),
    .p_ZL16post_spike_times_5_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_5_ce0),
    .p_ZL16post_spike_times_5_q0(p_ZL16post_spike_times_5_q0),
    .p_ZL16post_spike_times_4_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_4_address0),
    .p_ZL16post_spike_times_4_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_4_ce0),
    .p_ZL16post_spike_times_4_q0(p_ZL16post_spike_times_4_q0),
    .p_ZL16post_spike_times_3_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_3_address0),
    .p_ZL16post_spike_times_3_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_3_ce0),
    .p_ZL16post_spike_times_3_q0(p_ZL16post_spike_times_3_q0),
    .p_ZL16post_spike_times_2_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_2_address0),
    .p_ZL16post_spike_times_2_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_2_ce0),
    .p_ZL16post_spike_times_2_q0(p_ZL16post_spike_times_2_q0),
    .p_ZL16post_spike_times_1_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_1_address0),
    .p_ZL16post_spike_times_1_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_1_ce0),
    .p_ZL16post_spike_times_1_q0(p_ZL16post_spike_times_1_q0),
    .p_ZL16post_spike_times_0_address0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_0_address0),
    .p_ZL16post_spike_times_0_ce0(grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_0_ce0),
    .p_ZL16post_spike_times_0_q0(p_ZL16post_spike_times_0_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start_reg <= 1'b1;
        end else if ((grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_ready == 1'b1)) begin
            grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        shl_ln1_reg_388[15 : 8] <= shl_ln1_fu_345_p3[15 : 8];
        shl_ln_reg_383[15 : 8] <= shl_ln_fu_336_p3[15 : 8];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_0_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_0_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_1_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_1_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_2_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_2_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_3_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_3_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_4_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_4_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_5_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd5) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_5_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_6_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_6_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_7_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (trunc_ln88_fu_292_p1 == 3'd7) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_spike_times_7_we0_local = 1'b1;
    end else begin
        p_ZL15pre_spike_times_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_ap_start_reg;

assign lshr_ln_fu_296_p4 = {{pre_id[5:3]}};

assign p_ZL15pre_spike_times_0_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_0_ce0 = p_ZL15pre_spike_times_0_ce0_local;

assign p_ZL15pre_spike_times_0_d0 = current_time;

assign p_ZL15pre_spike_times_0_we0 = p_ZL15pre_spike_times_0_we0_local;

assign p_ZL15pre_spike_times_1_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_1_ce0 = p_ZL15pre_spike_times_1_ce0_local;

assign p_ZL15pre_spike_times_1_d0 = current_time;

assign p_ZL15pre_spike_times_1_we0 = p_ZL15pre_spike_times_1_we0_local;

assign p_ZL15pre_spike_times_2_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_2_ce0 = p_ZL15pre_spike_times_2_ce0_local;

assign p_ZL15pre_spike_times_2_d0 = current_time;

assign p_ZL15pre_spike_times_2_we0 = p_ZL15pre_spike_times_2_we0_local;

assign p_ZL15pre_spike_times_3_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_3_ce0 = p_ZL15pre_spike_times_3_ce0_local;

assign p_ZL15pre_spike_times_3_d0 = current_time;

assign p_ZL15pre_spike_times_3_we0 = p_ZL15pre_spike_times_3_we0_local;

assign p_ZL15pre_spike_times_4_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_4_ce0 = p_ZL15pre_spike_times_4_ce0_local;

assign p_ZL15pre_spike_times_4_d0 = current_time;

assign p_ZL15pre_spike_times_4_we0 = p_ZL15pre_spike_times_4_we0_local;

assign p_ZL15pre_spike_times_5_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_5_ce0 = p_ZL15pre_spike_times_5_ce0_local;

assign p_ZL15pre_spike_times_5_d0 = current_time;

assign p_ZL15pre_spike_times_5_we0 = p_ZL15pre_spike_times_5_we0_local;

assign p_ZL15pre_spike_times_6_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_6_ce0 = p_ZL15pre_spike_times_6_ce0_local;

assign p_ZL15pre_spike_times_6_d0 = current_time;

assign p_ZL15pre_spike_times_6_we0 = p_ZL15pre_spike_times_6_we0_local;

assign p_ZL15pre_spike_times_7_address0 = zext_ln88_fu_306_p1;

assign p_ZL15pre_spike_times_7_ce0 = p_ZL15pre_spike_times_7_ce0_local;

assign p_ZL15pre_spike_times_7_d0 = current_time;

assign p_ZL15pre_spike_times_7_we0 = p_ZL15pre_spike_times_7_we0_local;

assign p_ZL16post_spike_times_0_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_0_address0;

assign p_ZL16post_spike_times_0_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_0_ce0;

assign p_ZL16post_spike_times_1_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_1_address0;

assign p_ZL16post_spike_times_1_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_1_ce0;

assign p_ZL16post_spike_times_2_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_2_address0;

assign p_ZL16post_spike_times_2_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_2_ce0;

assign p_ZL16post_spike_times_3_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_3_address0;

assign p_ZL16post_spike_times_3_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_3_ce0;

assign p_ZL16post_spike_times_4_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_4_address0;

assign p_ZL16post_spike_times_4_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_4_ce0;

assign p_ZL16post_spike_times_5_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_5_address0;

assign p_ZL16post_spike_times_5_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_5_ce0;

assign p_ZL16post_spike_times_6_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_6_address0;

assign p_ZL16post_spike_times_6_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_6_ce0;

assign p_ZL16post_spike_times_7_address0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_7_address0;

assign p_ZL16post_spike_times_7_ce0 = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_p_ZL16post_spike_times_7_ce0;

assign shl_ln1_fu_345_p3 = {{params_tau_minus_val}, {8'd0}};

assign shl_ln_fu_336_p3 = {{params_tau_plus_val}, {8'd0}};

assign trunc_ln88_fu_292_p1 = pre_id[2:0];

assign weight_update_fifo_din = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_weight_update_fifo_din;

assign weight_update_fifo_write = grp_process_pre_spike_Pipeline_STDP_LTD_LOOP_fu_256_weight_update_fifo_write;

assign zext_ln88_fu_306_p1 = lshr_ln_fu_296_p4;

always @ (posedge ap_clk) begin
    shl_ln_reg_383[7:0] <= 8'b00000000;
    shl_ln1_reg_388[7:0] <= 8'b00000000;
end

endmodule //snn_top_hls_process_pre_spike
