// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZL13weight_memory_0_0_address1,
        p_ZL13weight_memory_0_0_ce1,
        p_ZL13weight_memory_0_0_we1,
        p_ZL13weight_memory_0_0_d1,
        p_ZL13weight_memory_0_1_address1,
        p_ZL13weight_memory_0_1_ce1,
        p_ZL13weight_memory_0_1_we1,
        p_ZL13weight_memory_0_1_d1,
        p_ZL13weight_memory_1_0_address1,
        p_ZL13weight_memory_1_0_ce1,
        p_ZL13weight_memory_1_0_we1,
        p_ZL13weight_memory_1_0_d1,
        p_ZL13weight_memory_1_1_address1,
        p_ZL13weight_memory_1_1_ce1,
        p_ZL13weight_memory_1_1_we1,
        p_ZL13weight_memory_1_1_d1,
        p_ZL13weight_memory_2_0_address1,
        p_ZL13weight_memory_2_0_ce1,
        p_ZL13weight_memory_2_0_we1,
        p_ZL13weight_memory_2_0_d1,
        p_ZL13weight_memory_2_1_address1,
        p_ZL13weight_memory_2_1_ce1,
        p_ZL13weight_memory_2_1_we1,
        p_ZL13weight_memory_2_1_d1,
        p_ZL13weight_memory_3_0_address1,
        p_ZL13weight_memory_3_0_ce1,
        p_ZL13weight_memory_3_0_we1,
        p_ZL13weight_memory_3_0_d1,
        p_ZL13weight_memory_3_1_address1,
        p_ZL13weight_memory_3_1_ce1,
        p_ZL13weight_memory_3_1_we1,
        p_ZL13weight_memory_3_1_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] p_ZL13weight_memory_0_0_address1;
output   p_ZL13weight_memory_0_0_ce1;
output   p_ZL13weight_memory_0_0_we1;
output  [7:0] p_ZL13weight_memory_0_0_d1;
output  [12:0] p_ZL13weight_memory_0_1_address1;
output   p_ZL13weight_memory_0_1_ce1;
output   p_ZL13weight_memory_0_1_we1;
output  [7:0] p_ZL13weight_memory_0_1_d1;
output  [12:0] p_ZL13weight_memory_1_0_address1;
output   p_ZL13weight_memory_1_0_ce1;
output   p_ZL13weight_memory_1_0_we1;
output  [7:0] p_ZL13weight_memory_1_0_d1;
output  [12:0] p_ZL13weight_memory_1_1_address1;
output   p_ZL13weight_memory_1_1_ce1;
output   p_ZL13weight_memory_1_1_we1;
output  [7:0] p_ZL13weight_memory_1_1_d1;
output  [12:0] p_ZL13weight_memory_2_0_address1;
output   p_ZL13weight_memory_2_0_ce1;
output   p_ZL13weight_memory_2_0_we1;
output  [7:0] p_ZL13weight_memory_2_0_d1;
output  [12:0] p_ZL13weight_memory_2_1_address1;
output   p_ZL13weight_memory_2_1_ce1;
output   p_ZL13weight_memory_2_1_we1;
output  [7:0] p_ZL13weight_memory_2_1_d1;
output  [12:0] p_ZL13weight_memory_3_0_address1;
output   p_ZL13weight_memory_3_0_ce1;
output   p_ZL13weight_memory_3_0_we1;
output  [7:0] p_ZL13weight_memory_3_0_d1;
output  [12:0] p_ZL13weight_memory_3_1_address1;
output   p_ZL13weight_memory_3_1_ce1;
output   p_ZL13weight_memory_3_1_we1;
output  [7:0] p_ZL13weight_memory_3_1_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln637_fu_250_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln638_fu_270_p2;
reg   [0:0] icmp_ln638_reg_398;
wire   [1:0] trunc_ln638_fu_284_p1;
reg   [1:0] trunc_ln638_reg_403;
reg   [5:0] lshr_ln3_reg_407;
wire   [63:0] zext_ln642_fu_356_p1;
wire    ap_block_pp0_stage0;
reg   [8:0] j_fu_76;
wire   [8:0] add_ln638_fu_308_p2;
wire    ap_loop_init;
reg   [8:0] i_3_fu_80;
wire   [8:0] select_ln637_1_fu_328_p3;
reg   [16:0] indvar_flatten_fu_84;
wire   [16:0] add_ln637_1_fu_256_p2;
reg   [16:0] ap_sig_allocacmp_indvar_flatten_load;
reg    p_ZL13weight_memory_2_0_we1_local;
wire   [0:0] trunc_ln637_fu_335_p1;
reg    p_ZL13weight_memory_2_0_ce1_local;
reg    p_ZL13weight_memory_2_1_we1_local;
reg    p_ZL13weight_memory_2_1_ce1_local;
reg    p_ZL13weight_memory_1_0_we1_local;
reg    p_ZL13weight_memory_1_0_ce1_local;
reg    p_ZL13weight_memory_1_1_we1_local;
reg    p_ZL13weight_memory_1_1_ce1_local;
reg    p_ZL13weight_memory_0_0_we1_local;
reg    p_ZL13weight_memory_0_0_ce1_local;
reg    p_ZL13weight_memory_0_1_we1_local;
reg    p_ZL13weight_memory_0_1_ce1_local;
reg    p_ZL13weight_memory_3_0_we1_local;
reg    p_ZL13weight_memory_3_0_ce1_local;
reg    p_ZL13weight_memory_3_1_we1_local;
reg    p_ZL13weight_memory_3_1_ce1_local;
wire   [8:0] select_ln637_fu_276_p3;
wire   [8:0] add_ln637_fu_322_p2;
wire   [6:0] tmp_s_fu_339_p4;
wire   [12:0] tmp_2_fu_349_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_76 = 9'd0;
#0 i_3_fu_80 = 9'd0;
#0 indvar_flatten_fu_84 = 17'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_3_fu_80 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_3_fu_80 <= select_ln637_1_fu_328_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln637_fu_250_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_84 <= add_ln637_1_fu_256_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_84 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_76 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_76 <= add_ln638_fu_308_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln638_reg_398 <= icmp_ln638_fu_270_p2;
        lshr_ln3_reg_407 <= {{select_ln637_fu_276_p3[7:2]}};
        trunc_ln638_reg_403 <= trunc_ln638_fu_284_p1;
    end
end

always @ (*) begin
    if (((icmp_ln637_fu_250_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 17'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_0_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd0) & (trunc_ln638_reg_403 == 2'd0))) begin
        p_ZL13weight_memory_0_0_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_0_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd1) & (trunc_ln638_reg_403 == 2'd0))) begin
        p_ZL13weight_memory_0_1_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_1_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd0) & (trunc_ln638_reg_403 == 2'd1))) begin
        p_ZL13weight_memory_1_0_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_1_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd1) & (trunc_ln638_reg_403 == 2'd1))) begin
        p_ZL13weight_memory_1_1_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_2_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd0) & (trunc_ln638_reg_403 == 2'd2))) begin
        p_ZL13weight_memory_2_0_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_2_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd1) & (trunc_ln638_reg_403 == 2'd2))) begin
        p_ZL13weight_memory_2_1_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_3_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd0) & (trunc_ln638_reg_403 == 2'd3))) begin
        p_ZL13weight_memory_3_0_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13weight_memory_3_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln637_fu_335_p1 == 1'd1) & (trunc_ln638_reg_403 == 2'd3))) begin
        p_ZL13weight_memory_3_1_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln637_1_fu_256_p2 = (ap_sig_allocacmp_indvar_flatten_load + 17'd1);

assign add_ln637_fu_322_p2 = (i_3_fu_80 + 9'd1);

assign add_ln638_fu_308_p2 = (select_ln637_fu_276_p3 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln637_fu_250_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln638_fu_270_p2 = ((j_fu_76 == 9'd256) ? 1'b1 : 1'b0);

assign p_ZL13weight_memory_0_0_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_0_0_ce1 = p_ZL13weight_memory_0_0_ce1_local;

assign p_ZL13weight_memory_0_0_d1 = 8'd0;

assign p_ZL13weight_memory_0_0_we1 = p_ZL13weight_memory_0_0_we1_local;

assign p_ZL13weight_memory_0_1_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_0_1_ce1 = p_ZL13weight_memory_0_1_ce1_local;

assign p_ZL13weight_memory_0_1_d1 = 8'd0;

assign p_ZL13weight_memory_0_1_we1 = p_ZL13weight_memory_0_1_we1_local;

assign p_ZL13weight_memory_1_0_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_1_0_ce1 = p_ZL13weight_memory_1_0_ce1_local;

assign p_ZL13weight_memory_1_0_d1 = 8'd0;

assign p_ZL13weight_memory_1_0_we1 = p_ZL13weight_memory_1_0_we1_local;

assign p_ZL13weight_memory_1_1_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_1_1_ce1 = p_ZL13weight_memory_1_1_ce1_local;

assign p_ZL13weight_memory_1_1_d1 = 8'd0;

assign p_ZL13weight_memory_1_1_we1 = p_ZL13weight_memory_1_1_we1_local;

assign p_ZL13weight_memory_2_0_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_2_0_ce1 = p_ZL13weight_memory_2_0_ce1_local;

assign p_ZL13weight_memory_2_0_d1 = 8'd0;

assign p_ZL13weight_memory_2_0_we1 = p_ZL13weight_memory_2_0_we1_local;

assign p_ZL13weight_memory_2_1_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_2_1_ce1 = p_ZL13weight_memory_2_1_ce1_local;

assign p_ZL13weight_memory_2_1_d1 = 8'd0;

assign p_ZL13weight_memory_2_1_we1 = p_ZL13weight_memory_2_1_we1_local;

assign p_ZL13weight_memory_3_0_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_3_0_ce1 = p_ZL13weight_memory_3_0_ce1_local;

assign p_ZL13weight_memory_3_0_d1 = 8'd0;

assign p_ZL13weight_memory_3_0_we1 = p_ZL13weight_memory_3_0_we1_local;

assign p_ZL13weight_memory_3_1_address1 = zext_ln642_fu_356_p1;

assign p_ZL13weight_memory_3_1_ce1 = p_ZL13weight_memory_3_1_ce1_local;

assign p_ZL13weight_memory_3_1_d1 = 8'd0;

assign p_ZL13weight_memory_3_1_we1 = p_ZL13weight_memory_3_1_we1_local;

assign select_ln637_1_fu_328_p3 = ((icmp_ln638_reg_398[0:0] == 1'b1) ? add_ln637_fu_322_p2 : i_3_fu_80);

assign select_ln637_fu_276_p3 = ((icmp_ln638_fu_270_p2[0:0] == 1'b1) ? 9'd0 : j_fu_76);

assign tmp_2_fu_349_p3 = {{tmp_s_fu_339_p4}, {lshr_ln3_reg_407}};

assign tmp_s_fu_339_p4 = {{select_ln637_1_fu_328_p3[7:1]}};

assign trunc_ln637_fu_335_p1 = select_ln637_1_fu_328_p3[0:0];

assign trunc_ln638_fu_284_p1 = select_ln637_fu_276_p3[1:0];

assign zext_ln642_fu_356_p1 = tmp_2_fu_349_p3;

endmodule //snn_top_hls_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER
