// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln230,
        sext_ln223,
        p_ZL18eligibility_traces_0_address0,
        p_ZL18eligibility_traces_0_ce0,
        p_ZL18eligibility_traces_0_q0,
        p_ZL18eligibility_traces_1_address0,
        p_ZL18eligibility_traces_1_ce0,
        p_ZL18eligibility_traces_1_q0,
        p_ZL18eligibility_traces_2_address0,
        p_ZL18eligibility_traces_2_ce0,
        p_ZL18eligibility_traces_2_q0,
        p_ZL18eligibility_traces_3_address0,
        p_ZL18eligibility_traces_3_ce0,
        p_ZL18eligibility_traces_3_q0,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_we1,
        p_ZL13weight_memory_0_d1,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_we1,
        p_ZL13weight_memory_1_d1,
        p_ZL13weight_memory_2_address0,
        p_ZL13weight_memory_2_ce0,
        p_ZL13weight_memory_2_q0,
        p_ZL13weight_memory_2_address1,
        p_ZL13weight_memory_2_ce1,
        p_ZL13weight_memory_2_we1,
        p_ZL13weight_memory_2_d1,
        p_ZL13weight_memory_3_address0,
        p_ZL13weight_memory_3_ce0,
        p_ZL13weight_memory_3_q0,
        p_ZL13weight_memory_3_address1,
        p_ZL13weight_memory_3_ce1,
        p_ZL13weight_memory_3_we1,
        p_ZL13weight_memory_3_d1,
        p_ZL13weight_memory_4_address0,
        p_ZL13weight_memory_4_ce0,
        p_ZL13weight_memory_4_q0,
        p_ZL13weight_memory_4_address1,
        p_ZL13weight_memory_4_ce1,
        p_ZL13weight_memory_4_we1,
        p_ZL13weight_memory_4_d1,
        p_ZL13weight_memory_5_address0,
        p_ZL13weight_memory_5_ce0,
        p_ZL13weight_memory_5_q0,
        p_ZL13weight_memory_5_address1,
        p_ZL13weight_memory_5_ce1,
        p_ZL13weight_memory_5_we1,
        p_ZL13weight_memory_5_d1,
        p_ZL13weight_memory_6_address0,
        p_ZL13weight_memory_6_ce0,
        p_ZL13weight_memory_6_q0,
        p_ZL13weight_memory_6_address1,
        p_ZL13weight_memory_6_ce1,
        p_ZL13weight_memory_6_we1,
        p_ZL13weight_memory_6_d1,
        p_ZL13weight_memory_7_address0,
        p_ZL13weight_memory_7_ce0,
        p_ZL13weight_memory_7_q0,
        p_ZL13weight_memory_7_address1,
        p_ZL13weight_memory_7_ce1,
        p_ZL13weight_memory_7_we1,
        p_ZL13weight_memory_7_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] sext_ln230;
input  [15:0] sext_ln223;
output  [9:0] p_ZL18eligibility_traces_0_address0;
output   p_ZL18eligibility_traces_0_ce0;
input  [15:0] p_ZL18eligibility_traces_0_q0;
output  [9:0] p_ZL18eligibility_traces_1_address0;
output   p_ZL18eligibility_traces_1_ce0;
input  [15:0] p_ZL18eligibility_traces_1_q0;
output  [9:0] p_ZL18eligibility_traces_2_address0;
output   p_ZL18eligibility_traces_2_ce0;
input  [15:0] p_ZL18eligibility_traces_2_q0;
output  [9:0] p_ZL18eligibility_traces_3_address0;
output   p_ZL18eligibility_traces_3_ce0;
input  [15:0] p_ZL18eligibility_traces_3_q0;
output  [8:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [8:0] p_ZL13weight_memory_0_address1;
output   p_ZL13weight_memory_0_ce1;
output   p_ZL13weight_memory_0_we1;
output  [7:0] p_ZL13weight_memory_0_d1;
output  [8:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [8:0] p_ZL13weight_memory_1_address1;
output   p_ZL13weight_memory_1_ce1;
output   p_ZL13weight_memory_1_we1;
output  [7:0] p_ZL13weight_memory_1_d1;
output  [8:0] p_ZL13weight_memory_2_address0;
output   p_ZL13weight_memory_2_ce0;
input  [7:0] p_ZL13weight_memory_2_q0;
output  [8:0] p_ZL13weight_memory_2_address1;
output   p_ZL13weight_memory_2_ce1;
output   p_ZL13weight_memory_2_we1;
output  [7:0] p_ZL13weight_memory_2_d1;
output  [8:0] p_ZL13weight_memory_3_address0;
output   p_ZL13weight_memory_3_ce0;
input  [7:0] p_ZL13weight_memory_3_q0;
output  [8:0] p_ZL13weight_memory_3_address1;
output   p_ZL13weight_memory_3_ce1;
output   p_ZL13weight_memory_3_we1;
output  [7:0] p_ZL13weight_memory_3_d1;
output  [8:0] p_ZL13weight_memory_4_address0;
output   p_ZL13weight_memory_4_ce0;
input  [7:0] p_ZL13weight_memory_4_q0;
output  [8:0] p_ZL13weight_memory_4_address1;
output   p_ZL13weight_memory_4_ce1;
output   p_ZL13weight_memory_4_we1;
output  [7:0] p_ZL13weight_memory_4_d1;
output  [8:0] p_ZL13weight_memory_5_address0;
output   p_ZL13weight_memory_5_ce0;
input  [7:0] p_ZL13weight_memory_5_q0;
output  [8:0] p_ZL13weight_memory_5_address1;
output   p_ZL13weight_memory_5_ce1;
output   p_ZL13weight_memory_5_we1;
output  [7:0] p_ZL13weight_memory_5_d1;
output  [8:0] p_ZL13weight_memory_6_address0;
output   p_ZL13weight_memory_6_ce0;
input  [7:0] p_ZL13weight_memory_6_q0;
output  [8:0] p_ZL13weight_memory_6_address1;
output   p_ZL13weight_memory_6_ce1;
output   p_ZL13weight_memory_6_we1;
output  [7:0] p_ZL13weight_memory_6_d1;
output  [8:0] p_ZL13weight_memory_7_address0;
output   p_ZL13weight_memory_7_ce0;
input  [7:0] p_ZL13weight_memory_7_q0;
output  [8:0] p_ZL13weight_memory_7_address1;
output   p_ZL13weight_memory_7_ce1;
output   p_ZL13weight_memory_7_we1;
output  [7:0] p_ZL13weight_memory_7_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln223_fu_394_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [39:0] sext_ln223_cast_fu_368_p1;
reg  signed [39:0] sext_ln223_cast_reg_763;
wire    ap_block_pp0_stage0_11001;
wire  signed [25:0] sext_ln230_cast_fu_372_p1;
reg  signed [25:0] sext_ln230_cast_reg_768;
wire   [5:0] trunc_ln224_fu_445_p1;
reg   [5:0] trunc_ln224_reg_777;
reg   [5:0] trunc_ln224_reg_777_pp0_iter2_reg;
wire   [1:0] trunc_ln224_1_fu_449_p1;
reg   [1:0] trunc_ln224_1_reg_782;
wire   [2:0] trunc_ln224_2_fu_453_p1;
reg   [2:0] trunc_ln224_2_reg_787;
reg   [2:0] trunc_ln224_2_reg_787_pp0_iter2_reg;
reg   [2:0] trunc_ln224_2_reg_787_pp0_iter3_reg;
reg   [2:0] trunc_ln224_2_reg_787_pp0_iter4_reg;
reg   [2:0] trunc_ln224_2_reg_787_pp0_iter5_reg;
reg   [2:0] lshr_ln_reg_793;
reg   [2:0] lshr_ln_reg_793_pp0_iter2_reg;
wire  signed [15:0] trace_fu_509_p11;
reg  signed [15:0] trace_reg_818;
wire   [0:0] icmp_ln228_fu_532_p2;
reg   [0:0] icmp_ln228_reg_823;
reg   [0:0] icmp_ln228_reg_823_pp0_iter3_reg;
reg   [0:0] icmp_ln228_reg_823_pp0_iter4_reg;
reg   [0:0] icmp_ln228_reg_823_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_0_addr_reg_827;
reg   [8:0] p_ZL13weight_memory_0_addr_reg_827_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_0_addr_reg_827_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_1_addr_reg_833;
reg   [8:0] p_ZL13weight_memory_1_addr_reg_833_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_1_addr_reg_833_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_2_addr_reg_839;
reg   [8:0] p_ZL13weight_memory_2_addr_reg_839_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_2_addr_reg_839_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_3_addr_reg_845;
reg   [8:0] p_ZL13weight_memory_3_addr_reg_845_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_3_addr_reg_845_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_4_addr_reg_851;
reg   [8:0] p_ZL13weight_memory_4_addr_reg_851_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_4_addr_reg_851_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_5_addr_reg_857;
reg   [8:0] p_ZL13weight_memory_5_addr_reg_857_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_5_addr_reg_857_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_6_addr_reg_863;
reg   [8:0] p_ZL13weight_memory_6_addr_reg_863_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_6_addr_reg_863_pp0_iter5_reg;
reg   [8:0] p_ZL13weight_memory_7_addr_reg_869;
reg   [8:0] p_ZL13weight_memory_7_addr_reg_869_pp0_iter4_reg;
reg   [8:0] p_ZL13weight_memory_7_addr_reg_869_pp0_iter5_reg;
wire   [25:0] mul_ln230_fu_559_p2;
reg  signed [25:0] mul_ln230_reg_875;
wire   [7:0] current_fu_581_p19;
reg   [7:0] current_reg_880;
wire  signed [39:0] mul_ln230_1_fu_364_p2;
reg  signed [39:0] mul_ln230_1_reg_885;
reg   [15:0] tmp_154_cast_reg_890;
wire   [16:0] trunc_ln230_fu_634_p1;
reg   [16:0] trunc_ln230_reg_897;
wire   [15:0] w_fu_684_p2;
reg   [15:0] w_reg_902;
wire   [0:0] icmp_ln70_fu_700_p2;
reg   [0:0] icmp_ln70_reg_908;
wire   [63:0] zext_ln227_fu_485_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln229_fu_544_p1;
reg   [6:0] j_fu_152;
wire   [6:0] add_ln224_fu_493_p2;
wire    ap_loop_init;
reg   [6:0] i_fu_156;
wire   [6:0] select_ln223_1_fu_437_p3;
reg   [12:0] indvar_flatten_fu_160;
wire   [12:0] add_ln223_1_fu_400_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
reg    p_ZL18eligibility_traces_0_ce0_local;
reg    p_ZL18eligibility_traces_1_ce0_local;
reg    p_ZL18eligibility_traces_2_ce0_local;
reg    p_ZL18eligibility_traces_3_ce0_local;
reg    p_ZL13weight_memory_0_ce0_local;
reg    p_ZL13weight_memory_0_we1_local;
wire   [7:0] select_ln70_fu_726_p3;
reg    p_ZL13weight_memory_0_ce1_local;
reg    p_ZL13weight_memory_1_ce0_local;
reg    p_ZL13weight_memory_1_we1_local;
reg    p_ZL13weight_memory_1_ce1_local;
reg    p_ZL13weight_memory_2_ce0_local;
reg    p_ZL13weight_memory_2_we1_local;
reg    p_ZL13weight_memory_2_ce1_local;
reg    p_ZL13weight_memory_3_ce0_local;
reg    p_ZL13weight_memory_3_we1_local;
reg    p_ZL13weight_memory_3_ce1_local;
reg    p_ZL13weight_memory_4_ce0_local;
reg    p_ZL13weight_memory_4_we1_local;
reg    p_ZL13weight_memory_4_ce1_local;
reg    p_ZL13weight_memory_5_ce0_local;
reg    p_ZL13weight_memory_5_we1_local;
reg    p_ZL13weight_memory_5_ce1_local;
reg    p_ZL13weight_memory_6_ce0_local;
reg    p_ZL13weight_memory_6_we1_local;
reg    p_ZL13weight_memory_6_ce1_local;
reg    p_ZL13weight_memory_7_ce0_local;
reg    p_ZL13weight_memory_7_we1_local;
reg    p_ZL13weight_memory_7_ce1_local;
wire  signed [15:0] mul_ln230_1_fu_364_p1;
wire   [0:0] icmp_ln224_fu_423_p2;
wire   [6:0] add_ln223_fu_417_p2;
wire   [6:0] select_ln223_fu_429_p3;
wire   [3:0] lshr_ln224_1_fu_467_p4;
wire   [9:0] tmp_113_fu_477_p3;
wire   [15:0] trace_fu_509_p9;
wire   [8:0] tmp_s_fu_538_p3;
wire  signed [9:0] mul_ln230_fu_559_p1;
wire   [7:0] current_fu_581_p17;
wire  signed [41:0] sext_ln230_3_fu_638_p1;
wire   [23:0] tmp_114_fu_649_p3;
wire   [0:0] icmp_ln230_fu_656_p2;
wire   [15:0] add_ln230_fu_662_p2;
wire   [0:0] tmp_fu_641_p3;
wire   [15:0] select_ln230_fu_667_p3;
wire   [15:0] delta_fu_674_p3;
wire  signed [15:0] sext_ln231_fu_681_p1;
wire   [8:0] tmp_115_fu_690_p4;
wire   [0:0] icmp_ln71_fu_706_p2;
wire   [0:0] or_ln70_fu_721_p2;
wire   [7:0] select_ln70_2_fu_714_p3;
wire   [7:0] trunc_ln72_fu_711_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] trace_fu_509_p1;
wire   [1:0] trace_fu_509_p3;
wire  signed [1:0] trace_fu_509_p5;
wire  signed [1:0] trace_fu_509_p7;
wire   [2:0] current_fu_581_p1;
wire   [2:0] current_fu_581_p3;
wire   [2:0] current_fu_581_p5;
wire   [2:0] current_fu_581_p7;
wire  signed [2:0] current_fu_581_p9;
wire  signed [2:0] current_fu_581_p11;
wire  signed [2:0] current_fu_581_p13;
wire  signed [2:0] current_fu_581_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 j_fu_152 = 7'd0;
#0 i_fu_156 = 7'd0;
#0 indvar_flatten_fu_160 = 13'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_mul_26s_16s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 40 ))
mul_26s_16s_40_1_1_U222(
    .din0(mul_ln230_reg_875),
    .din1(mul_ln230_1_fu_364_p1),
    .dout(mul_ln230_1_fu_364_p2)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U223(
    .din0(p_ZL18eligibility_traces_0_q0),
    .din1(p_ZL18eligibility_traces_1_q0),
    .din2(p_ZL18eligibility_traces_2_q0),
    .din3(p_ZL18eligibility_traces_3_q0),
    .def(trace_fu_509_p9),
    .sel(trunc_ln224_1_reg_782),
    .dout(trace_fu_509_p11)
);

snn_top_hls_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U224(
    .din0(trace_reg_818),
    .din1(mul_ln230_fu_559_p1),
    .dout(mul_ln230_fu_559_p2)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U225(
    .din0(p_ZL13weight_memory_0_q0),
    .din1(p_ZL13weight_memory_1_q0),
    .din2(p_ZL13weight_memory_2_q0),
    .din3(p_ZL13weight_memory_3_q0),
    .din4(p_ZL13weight_memory_4_q0),
    .din5(p_ZL13weight_memory_5_q0),
    .din6(p_ZL13weight_memory_6_q0),
    .din7(p_ZL13weight_memory_7_q0),
    .def(current_fu_581_p17),
    .sel(trunc_ln224_2_reg_787_pp0_iter3_reg),
    .dout(current_fu_581_p19)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_156 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_156 <= select_ln223_1_fu_437_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln223_fu_394_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_160 <= add_ln223_1_fu_400_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_160 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_152 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_152 <= add_ln224_fu_493_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln_reg_793 <= {{select_ln223_fu_429_p3[5:3]}};
        sext_ln223_cast_reg_763 <= sext_ln223_cast_fu_368_p1;
        sext_ln230_cast_reg_768 <= sext_ln230_cast_fu_372_p1;
        trunc_ln224_1_reg_782 <= trunc_ln224_1_fu_449_p1;
        trunc_ln224_2_reg_787 <= trunc_ln224_2_fu_453_p1;
        trunc_ln224_reg_777 <= trunc_ln224_fu_445_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        current_reg_880 <= current_fu_581_p19;
        icmp_ln228_reg_823 <= icmp_ln228_fu_532_p2;
        icmp_ln228_reg_823_pp0_iter3_reg <= icmp_ln228_reg_823;
        icmp_ln228_reg_823_pp0_iter4_reg <= icmp_ln228_reg_823_pp0_iter3_reg;
        icmp_ln228_reg_823_pp0_iter5_reg <= icmp_ln228_reg_823_pp0_iter4_reg;
        icmp_ln70_reg_908 <= icmp_ln70_fu_700_p2;
        lshr_ln_reg_793_pp0_iter2_reg <= lshr_ln_reg_793;
        mul_ln230_1_reg_885 <= mul_ln230_1_fu_364_p2;
        mul_ln230_reg_875 <= mul_ln230_fu_559_p2;
        p_ZL13weight_memory_0_addr_reg_827 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_0_addr_reg_827_pp0_iter4_reg <= p_ZL13weight_memory_0_addr_reg_827;
        p_ZL13weight_memory_0_addr_reg_827_pp0_iter5_reg <= p_ZL13weight_memory_0_addr_reg_827_pp0_iter4_reg;
        p_ZL13weight_memory_1_addr_reg_833 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_1_addr_reg_833_pp0_iter4_reg <= p_ZL13weight_memory_1_addr_reg_833;
        p_ZL13weight_memory_1_addr_reg_833_pp0_iter5_reg <= p_ZL13weight_memory_1_addr_reg_833_pp0_iter4_reg;
        p_ZL13weight_memory_2_addr_reg_839 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_2_addr_reg_839_pp0_iter4_reg <= p_ZL13weight_memory_2_addr_reg_839;
        p_ZL13weight_memory_2_addr_reg_839_pp0_iter5_reg <= p_ZL13weight_memory_2_addr_reg_839_pp0_iter4_reg;
        p_ZL13weight_memory_3_addr_reg_845 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_3_addr_reg_845_pp0_iter4_reg <= p_ZL13weight_memory_3_addr_reg_845;
        p_ZL13weight_memory_3_addr_reg_845_pp0_iter5_reg <= p_ZL13weight_memory_3_addr_reg_845_pp0_iter4_reg;
        p_ZL13weight_memory_4_addr_reg_851 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_4_addr_reg_851_pp0_iter4_reg <= p_ZL13weight_memory_4_addr_reg_851;
        p_ZL13weight_memory_4_addr_reg_851_pp0_iter5_reg <= p_ZL13weight_memory_4_addr_reg_851_pp0_iter4_reg;
        p_ZL13weight_memory_5_addr_reg_857 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_5_addr_reg_857_pp0_iter4_reg <= p_ZL13weight_memory_5_addr_reg_857;
        p_ZL13weight_memory_5_addr_reg_857_pp0_iter5_reg <= p_ZL13weight_memory_5_addr_reg_857_pp0_iter4_reg;
        p_ZL13weight_memory_6_addr_reg_863 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_6_addr_reg_863_pp0_iter4_reg <= p_ZL13weight_memory_6_addr_reg_863;
        p_ZL13weight_memory_6_addr_reg_863_pp0_iter5_reg <= p_ZL13weight_memory_6_addr_reg_863_pp0_iter4_reg;
        p_ZL13weight_memory_7_addr_reg_869 <= zext_ln229_fu_544_p1;
        p_ZL13weight_memory_7_addr_reg_869_pp0_iter4_reg <= p_ZL13weight_memory_7_addr_reg_869;
        p_ZL13weight_memory_7_addr_reg_869_pp0_iter5_reg <= p_ZL13weight_memory_7_addr_reg_869_pp0_iter4_reg;
        tmp_154_cast_reg_890 <= {{mul_ln230_1_fu_364_p2[32:17]}};
        trace_reg_818 <= trace_fu_509_p11;
        trunc_ln224_2_reg_787_pp0_iter2_reg <= trunc_ln224_2_reg_787;
        trunc_ln224_2_reg_787_pp0_iter3_reg <= trunc_ln224_2_reg_787_pp0_iter2_reg;
        trunc_ln224_2_reg_787_pp0_iter4_reg <= trunc_ln224_2_reg_787_pp0_iter3_reg;
        trunc_ln224_2_reg_787_pp0_iter5_reg <= trunc_ln224_2_reg_787_pp0_iter4_reg;
        trunc_ln224_reg_777_pp0_iter2_reg <= trunc_ln224_reg_777;
        trunc_ln230_reg_897 <= trunc_ln230_fu_634_p1;
        w_reg_902 <= w_fu_684_p2;
    end
end

always @ (*) begin
    if (((icmp_ln223_fu_394_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_0_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd0))) begin
        p_ZL13weight_memory_0_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_1_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd1))) begin
        p_ZL13weight_memory_1_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_2_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_2_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd2))) begin
        p_ZL13weight_memory_2_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_3_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_3_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd3))) begin
        p_ZL13weight_memory_3_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_4_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_4_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd4))) begin
        p_ZL13weight_memory_4_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_5_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_5_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd5))) begin
        p_ZL13weight_memory_5_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_6_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_6_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd6))) begin
        p_ZL13weight_memory_6_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL13weight_memory_7_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL13weight_memory_7_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln228_reg_823_pp0_iter5_reg == 1'd0) & (trunc_ln224_2_reg_787_pp0_iter5_reg == 3'd7))) begin
        p_ZL13weight_memory_7_we1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL18eligibility_traces_0_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL18eligibility_traces_1_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL18eligibility_traces_2_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL18eligibility_traces_3_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln223_1_fu_400_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln223_fu_417_p2 = (i_fu_156 + 7'd1);

assign add_ln224_fu_493_p2 = (select_ln223_fu_429_p3 + 7'd1);

assign add_ln230_fu_662_p2 = (tmp_154_cast_reg_890 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign current_fu_581_p17 = 'bx;

assign delta_fu_674_p3 = ((tmp_fu_641_p3[0:0] == 1'b1) ? select_ln230_fu_667_p3 : tmp_154_cast_reg_890);

assign icmp_ln223_fu_394_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_423_p2 = ((j_fu_152 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln228_fu_532_p2 = ((trace_fu_509_p11 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_656_p2 = ((tmp_114_fu_649_p3 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_700_p2 = (($signed(tmp_115_fu_690_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_706_p2 = (($signed(w_reg_902) < $signed(16'd65408)) ? 1'b1 : 1'b0);

assign lshr_ln224_1_fu_467_p4 = {{select_ln223_fu_429_p3[5:2]}};

assign mul_ln230_1_fu_364_p1 = sext_ln223_cast_reg_763;

assign mul_ln230_fu_559_p1 = sext_ln230_cast_reg_768;

assign or_ln70_fu_721_p2 = (icmp_ln71_fu_706_p2 | icmp_ln70_reg_908);

assign p_ZL13weight_memory_0_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_0_address1 = p_ZL13weight_memory_0_addr_reg_827_pp0_iter5_reg;

assign p_ZL13weight_memory_0_ce0 = p_ZL13weight_memory_0_ce0_local;

assign p_ZL13weight_memory_0_ce1 = p_ZL13weight_memory_0_ce1_local;

assign p_ZL13weight_memory_0_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_0_we1 = p_ZL13weight_memory_0_we1_local;

assign p_ZL13weight_memory_1_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_1_address1 = p_ZL13weight_memory_1_addr_reg_833_pp0_iter5_reg;

assign p_ZL13weight_memory_1_ce0 = p_ZL13weight_memory_1_ce0_local;

assign p_ZL13weight_memory_1_ce1 = p_ZL13weight_memory_1_ce1_local;

assign p_ZL13weight_memory_1_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_1_we1 = p_ZL13weight_memory_1_we1_local;

assign p_ZL13weight_memory_2_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_2_address1 = p_ZL13weight_memory_2_addr_reg_839_pp0_iter5_reg;

assign p_ZL13weight_memory_2_ce0 = p_ZL13weight_memory_2_ce0_local;

assign p_ZL13weight_memory_2_ce1 = p_ZL13weight_memory_2_ce1_local;

assign p_ZL13weight_memory_2_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_2_we1 = p_ZL13weight_memory_2_we1_local;

assign p_ZL13weight_memory_3_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_3_address1 = p_ZL13weight_memory_3_addr_reg_845_pp0_iter5_reg;

assign p_ZL13weight_memory_3_ce0 = p_ZL13weight_memory_3_ce0_local;

assign p_ZL13weight_memory_3_ce1 = p_ZL13weight_memory_3_ce1_local;

assign p_ZL13weight_memory_3_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_3_we1 = p_ZL13weight_memory_3_we1_local;

assign p_ZL13weight_memory_4_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_4_address1 = p_ZL13weight_memory_4_addr_reg_851_pp0_iter5_reg;

assign p_ZL13weight_memory_4_ce0 = p_ZL13weight_memory_4_ce0_local;

assign p_ZL13weight_memory_4_ce1 = p_ZL13weight_memory_4_ce1_local;

assign p_ZL13weight_memory_4_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_4_we1 = p_ZL13weight_memory_4_we1_local;

assign p_ZL13weight_memory_5_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_5_address1 = p_ZL13weight_memory_5_addr_reg_857_pp0_iter5_reg;

assign p_ZL13weight_memory_5_ce0 = p_ZL13weight_memory_5_ce0_local;

assign p_ZL13weight_memory_5_ce1 = p_ZL13weight_memory_5_ce1_local;

assign p_ZL13weight_memory_5_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_5_we1 = p_ZL13weight_memory_5_we1_local;

assign p_ZL13weight_memory_6_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_6_address1 = p_ZL13weight_memory_6_addr_reg_863_pp0_iter5_reg;

assign p_ZL13weight_memory_6_ce0 = p_ZL13weight_memory_6_ce0_local;

assign p_ZL13weight_memory_6_ce1 = p_ZL13weight_memory_6_ce1_local;

assign p_ZL13weight_memory_6_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_6_we1 = p_ZL13weight_memory_6_we1_local;

assign p_ZL13weight_memory_7_address0 = zext_ln229_fu_544_p1;

assign p_ZL13weight_memory_7_address1 = p_ZL13weight_memory_7_addr_reg_869_pp0_iter5_reg;

assign p_ZL13weight_memory_7_ce0 = p_ZL13weight_memory_7_ce0_local;

assign p_ZL13weight_memory_7_ce1 = p_ZL13weight_memory_7_ce1_local;

assign p_ZL13weight_memory_7_d1 = select_ln70_fu_726_p3;

assign p_ZL13weight_memory_7_we1 = p_ZL13weight_memory_7_we1_local;

assign p_ZL18eligibility_traces_0_address0 = zext_ln227_fu_485_p1;

assign p_ZL18eligibility_traces_0_ce0 = p_ZL18eligibility_traces_0_ce0_local;

assign p_ZL18eligibility_traces_1_address0 = zext_ln227_fu_485_p1;

assign p_ZL18eligibility_traces_1_ce0 = p_ZL18eligibility_traces_1_ce0_local;

assign p_ZL18eligibility_traces_2_address0 = zext_ln227_fu_485_p1;

assign p_ZL18eligibility_traces_2_ce0 = p_ZL18eligibility_traces_2_ce0_local;

assign p_ZL18eligibility_traces_3_address0 = zext_ln227_fu_485_p1;

assign p_ZL18eligibility_traces_3_ce0 = p_ZL18eligibility_traces_3_ce0_local;

assign select_ln223_1_fu_437_p3 = ((icmp_ln224_fu_423_p2[0:0] == 1'b1) ? add_ln223_fu_417_p2 : i_fu_156);

assign select_ln223_fu_429_p3 = ((icmp_ln224_fu_423_p2[0:0] == 1'b1) ? 7'd0 : j_fu_152);

assign select_ln230_fu_667_p3 = ((icmp_ln230_fu_656_p2[0:0] == 1'b1) ? add_ln230_fu_662_p2 : tmp_154_cast_reg_890);

assign select_ln70_2_fu_714_p3 = ((icmp_ln70_reg_908[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln70_fu_726_p3 = ((or_ln70_fu_721_p2[0:0] == 1'b1) ? select_ln70_2_fu_714_p3 : trunc_ln72_fu_711_p1);

assign sext_ln223_cast_fu_368_p1 = $signed(sext_ln223);

assign sext_ln230_3_fu_638_p1 = mul_ln230_1_reg_885;

assign sext_ln230_cast_fu_372_p1 = $signed(sext_ln230);

assign sext_ln231_fu_681_p1 = $signed(current_reg_880);

assign tmp_113_fu_477_p3 = {{trunc_ln224_fu_445_p1}, {lshr_ln224_1_fu_467_p4}};

assign tmp_114_fu_649_p3 = {{trunc_ln230_reg_897}, {7'd0}};

assign tmp_115_fu_690_p4 = {{w_fu_684_p2[15:7]}};

assign tmp_fu_641_p3 = sext_ln230_3_fu_638_p1[32'd41];

assign tmp_s_fu_538_p3 = {{trunc_ln224_reg_777_pp0_iter2_reg}, {lshr_ln_reg_793_pp0_iter2_reg}};

assign trace_fu_509_p9 = 'bx;

assign trunc_ln224_1_fu_449_p1 = select_ln223_fu_429_p3[1:0];

assign trunc_ln224_2_fu_453_p1 = select_ln223_fu_429_p3[2:0];

assign trunc_ln224_fu_445_p1 = select_ln223_1_fu_437_p3[5:0];

assign trunc_ln230_fu_634_p1 = mul_ln230_1_fu_364_p2[16:0];

assign trunc_ln72_fu_711_p1 = w_reg_902[7:0];

assign w_fu_684_p2 = ($signed(delta_fu_674_p3) + $signed(sext_ln231_fu_681_p1));

assign zext_ln227_fu_485_p1 = tmp_113_fu_477_p3;

assign zext_ln229_fu_544_p1 = tmp_s_fu_538_p3;

endmodule //snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER
