-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL13weight_memory_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_0_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_1_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_2_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_3_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_4_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_4_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_5_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_5_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_6_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_6_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_7_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_7_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of snn_top_hls_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln379_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln380_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln380_reg_402 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln380_1_fu_290_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln380_1_reg_407 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln2_reg_411 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln382_fu_360_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_1_fu_82 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln380_fu_322_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_86 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln379_1_fu_342_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten6_fu_90 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln379_1_fu_262_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (12 downto 0);
    signal p_ZL13weight_memory_6_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_6_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_5_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_5_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_4_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_4_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_3_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_3_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_2_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_2_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_7_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_7_ce1_local : STD_LOGIC;
    signal select_ln379_fu_282_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln379_fu_336_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln380_fu_349_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_353_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_86 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    i_fu_86 <= select_ln379_1_fu_342_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln379_fu_256_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_90 <= add_ln379_1_fu_262_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_90 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    j_1_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_1_fu_82 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_1_fu_82 <= add_ln380_fu_322_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln380_reg_402 <= icmp_ln380_fu_276_p2;
                lshr_ln2_reg_411 <= select_ln379_fu_282_p3(5 downto 3);
                trunc_ln380_1_reg_407 <= trunc_ln380_1_fu_290_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln379_1_fu_262_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv13_1));
    add_ln379_fu_336_p2 <= std_logic_vector(unsigned(i_fu_86) + unsigned(ap_const_lv7_1));
    add_ln380_fu_322_p2 <= std_logic_vector(unsigned(select_ln379_fu_282_p3) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln379_fu_256_p2)
    begin
        if (((icmp_ln379_fu_256_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_90)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_90;
        end if; 
    end process;

    icmp_ln379_fu_256_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv13_1000) else "0";
    icmp_ln380_fu_276_p2 <= "1" when (j_1_fu_82 = ap_const_lv7_40) else "0";
    p_ZL13weight_memory_0_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_0_ce1 <= p_ZL13weight_memory_0_ce1_local;

    p_ZL13weight_memory_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_0_we1 <= p_ZL13weight_memory_0_we1_local;

    p_ZL13weight_memory_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_0))) then 
            p_ZL13weight_memory_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_1_ce1 <= p_ZL13weight_memory_1_ce1_local;

    p_ZL13weight_memory_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_1_we1 <= p_ZL13weight_memory_1_we1_local;

    p_ZL13weight_memory_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_1))) then 
            p_ZL13weight_memory_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_2_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_2_ce1 <= p_ZL13weight_memory_2_ce1_local;

    p_ZL13weight_memory_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_2_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_2_we1 <= p_ZL13weight_memory_2_we1_local;

    p_ZL13weight_memory_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_2))) then 
            p_ZL13weight_memory_2_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_3_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_3_ce1 <= p_ZL13weight_memory_3_ce1_local;

    p_ZL13weight_memory_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_3_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_3_we1 <= p_ZL13weight_memory_3_we1_local;

    p_ZL13weight_memory_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_3))) then 
            p_ZL13weight_memory_3_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_4_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_4_ce1 <= p_ZL13weight_memory_4_ce1_local;

    p_ZL13weight_memory_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_4_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_4_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_4_we1 <= p_ZL13weight_memory_4_we1_local;

    p_ZL13weight_memory_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_4))) then 
            p_ZL13weight_memory_4_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_5_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_5_ce1 <= p_ZL13weight_memory_5_ce1_local;

    p_ZL13weight_memory_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_5_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_5_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_5_we1 <= p_ZL13weight_memory_5_we1_local;

    p_ZL13weight_memory_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_5))) then 
            p_ZL13weight_memory_5_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_6_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_6_ce1 <= p_ZL13weight_memory_6_ce1_local;

    p_ZL13weight_memory_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_6_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_6_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_6_we1 <= p_ZL13weight_memory_6_we1_local;

    p_ZL13weight_memory_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_6))) then 
            p_ZL13weight_memory_6_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_7_address1 <= zext_ln382_fu_360_p1(9 - 1 downto 0);
    p_ZL13weight_memory_7_ce1 <= p_ZL13weight_memory_7_ce1_local;

    p_ZL13weight_memory_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_7_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_7_d1 <= ap_const_lv8_0;
    p_ZL13weight_memory_7_we1 <= p_ZL13weight_memory_7_we1_local;

    p_ZL13weight_memory_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln380_1_reg_407)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln380_1_reg_407 = ap_const_lv3_7))) then 
            p_ZL13weight_memory_7_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln379_1_fu_342_p3 <= 
        add_ln379_fu_336_p2 when (icmp_ln380_reg_402(0) = '1') else 
        i_fu_86;
    select_ln379_fu_282_p3 <= 
        ap_const_lv7_0 when (icmp_ln380_fu_276_p2(0) = '1') else 
        j_1_fu_82;
    tmp_s_fu_353_p3 <= (trunc_ln380_fu_349_p1 & lshr_ln2_reg_411);
    trunc_ln380_1_fu_290_p1 <= select_ln379_fu_282_p3(3 - 1 downto 0);
    trunc_ln380_fu_349_p1 <= select_ln379_1_fu_342_p3(6 - 1 downto 0);
    zext_ln382_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_353_p3),64));
end behav;
