-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_apply_reward_signal is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    reward_signal : IN STD_LOGIC_VECTOR (7 downto 0);
    params_learning_rate_val : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_0_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_1_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_2_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_3_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL13weight_memory_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_0_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_0_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_1_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_1_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_2_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_2_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_3_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_3_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_4_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_4_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_4_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_5_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_5_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_5_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_6_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_6_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_6_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_7_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_7_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_7_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of snn_top_hls_apply_reward_signal is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln219_fu_109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln219_reg_183 : STD_LOGIC_VECTOR (0 downto 0);
    signal reward_factor_fu_169_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal reward_factor_reg_187 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_idle : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_ready : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce0 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_we1 : STD_LOGIC;
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_ln221_1_fu_115_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln221_fu_123_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln221_2_fu_141_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln221_1_fu_149_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln221_fu_135_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_fu_127_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_159_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln221_1_fu_153_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln230 : IN STD_LOGIC_VECTOR (9 downto 0);
        sext_ln223 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL18eligibility_traces_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL18eligibility_traces_0_ce0 : OUT STD_LOGIC;
        p_ZL18eligibility_traces_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL18eligibility_traces_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL18eligibility_traces_1_ce0 : OUT STD_LOGIC;
        p_ZL18eligibility_traces_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL18eligibility_traces_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL18eligibility_traces_2_ce0 : OUT STD_LOGIC;
        p_ZL18eligibility_traces_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL18eligibility_traces_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_ZL18eligibility_traces_3_ce0 : OUT STD_LOGIC;
        p_ZL18eligibility_traces_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL13weight_memory_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_0_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_0_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_0_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_1_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_1_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_1_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_2_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_2_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_2_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_3_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_3_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_3_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_4_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_4_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_4_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_4_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_5_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_5_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_5_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_5_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_5_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_6_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_6_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_6_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_6_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_6_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_7_ce0 : OUT STD_LOGIC;
        p_ZL13weight_memory_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZL13weight_memory_7_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        p_ZL13weight_memory_7_ce1 : OUT STD_LOGIC;
        p_ZL13weight_memory_7_we1 : OUT STD_LOGIC;
        p_ZL13weight_memory_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78 : component snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start,
        ap_done => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done,
        ap_idle => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_idle,
        ap_ready => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_ready,
        sext_ln230 => reward_factor_reg_187,
        sext_ln223 => params_learning_rate_val,
        p_ZL18eligibility_traces_0_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_address0,
        p_ZL18eligibility_traces_0_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_ce0,
        p_ZL18eligibility_traces_0_q0 => p_ZL18eligibility_traces_0_q0,
        p_ZL18eligibility_traces_1_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_address0,
        p_ZL18eligibility_traces_1_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_ce0,
        p_ZL18eligibility_traces_1_q0 => p_ZL18eligibility_traces_1_q0,
        p_ZL18eligibility_traces_2_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_address0,
        p_ZL18eligibility_traces_2_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_ce0,
        p_ZL18eligibility_traces_2_q0 => p_ZL18eligibility_traces_2_q0,
        p_ZL18eligibility_traces_3_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_address0,
        p_ZL18eligibility_traces_3_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_ce0,
        p_ZL18eligibility_traces_3_q0 => p_ZL18eligibility_traces_3_q0,
        p_ZL13weight_memory_0_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0 => p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_we1,
        p_ZL13weight_memory_0_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_d1,
        p_ZL13weight_memory_1_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0 => p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_we1,
        p_ZL13weight_memory_1_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_d1,
        p_ZL13weight_memory_2_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address0,
        p_ZL13weight_memory_2_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce0,
        p_ZL13weight_memory_2_q0 => p_ZL13weight_memory_2_q0,
        p_ZL13weight_memory_2_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address1,
        p_ZL13weight_memory_2_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce1,
        p_ZL13weight_memory_2_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_we1,
        p_ZL13weight_memory_2_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_d1,
        p_ZL13weight_memory_3_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address0,
        p_ZL13weight_memory_3_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce0,
        p_ZL13weight_memory_3_q0 => p_ZL13weight_memory_3_q0,
        p_ZL13weight_memory_3_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address1,
        p_ZL13weight_memory_3_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce1,
        p_ZL13weight_memory_3_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_we1,
        p_ZL13weight_memory_3_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_d1,
        p_ZL13weight_memory_4_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address0,
        p_ZL13weight_memory_4_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce0,
        p_ZL13weight_memory_4_q0 => p_ZL13weight_memory_4_q0,
        p_ZL13weight_memory_4_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address1,
        p_ZL13weight_memory_4_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce1,
        p_ZL13weight_memory_4_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_we1,
        p_ZL13weight_memory_4_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_d1,
        p_ZL13weight_memory_5_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address0,
        p_ZL13weight_memory_5_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce0,
        p_ZL13weight_memory_5_q0 => p_ZL13weight_memory_5_q0,
        p_ZL13weight_memory_5_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address1,
        p_ZL13weight_memory_5_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce1,
        p_ZL13weight_memory_5_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_we1,
        p_ZL13weight_memory_5_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_d1,
        p_ZL13weight_memory_6_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address0,
        p_ZL13weight_memory_6_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce0,
        p_ZL13weight_memory_6_q0 => p_ZL13weight_memory_6_q0,
        p_ZL13weight_memory_6_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address1,
        p_ZL13weight_memory_6_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce1,
        p_ZL13weight_memory_6_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_we1,
        p_ZL13weight_memory_6_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_d1,
        p_ZL13weight_memory_7_address0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address0,
        p_ZL13weight_memory_7_ce0 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce0,
        p_ZL13weight_memory_7_q0 => p_ZL13weight_memory_7_q0,
        p_ZL13weight_memory_7_address1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address1,
        p_ZL13weight_memory_7_ce1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce1,
        p_ZL13weight_memory_7_we1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_we1,
        p_ZL13weight_memory_7_d1 => grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln219_fu_109_p2 = ap_const_lv1_0))) then 
                    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln219_reg_183 <= icmp_ln219_fu_109_p2;
                    reward_factor_reg_187(9 downto 1) <= reward_factor_fu_169_p3(9 downto 1);
            end if;
        end if;
    end process;
    reward_factor_reg_187(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(icmp_ln219_reg_183, grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_done = ap_const_logic_0) and (icmp_ln219_reg_183 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_ap_start_reg;
    icmp_ln219_fu_109_p2 <= "1" when (reward_signal = ap_const_lv8_0) else "0";
    p_ZL13weight_memory_0_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address0;
    p_ZL13weight_memory_0_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_address1;
    p_ZL13weight_memory_0_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce0;
    p_ZL13weight_memory_0_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_ce1;
    p_ZL13weight_memory_0_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_d1;
    p_ZL13weight_memory_0_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_0_we1;
    p_ZL13weight_memory_1_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address0;
    p_ZL13weight_memory_1_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_address1;
    p_ZL13weight_memory_1_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce0;
    p_ZL13weight_memory_1_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_ce1;
    p_ZL13weight_memory_1_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_d1;
    p_ZL13weight_memory_1_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_1_we1;
    p_ZL13weight_memory_2_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address0;
    p_ZL13weight_memory_2_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_address1;
    p_ZL13weight_memory_2_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce0;
    p_ZL13weight_memory_2_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_ce1;
    p_ZL13weight_memory_2_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_d1;
    p_ZL13weight_memory_2_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_2_we1;
    p_ZL13weight_memory_3_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address0;
    p_ZL13weight_memory_3_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_address1;
    p_ZL13weight_memory_3_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce0;
    p_ZL13weight_memory_3_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_ce1;
    p_ZL13weight_memory_3_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_d1;
    p_ZL13weight_memory_3_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_3_we1;
    p_ZL13weight_memory_4_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address0;
    p_ZL13weight_memory_4_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_address1;
    p_ZL13weight_memory_4_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce0;
    p_ZL13weight_memory_4_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_ce1;
    p_ZL13weight_memory_4_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_d1;
    p_ZL13weight_memory_4_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_4_we1;
    p_ZL13weight_memory_5_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address0;
    p_ZL13weight_memory_5_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_address1;
    p_ZL13weight_memory_5_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce0;
    p_ZL13weight_memory_5_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_ce1;
    p_ZL13weight_memory_5_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_d1;
    p_ZL13weight_memory_5_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_5_we1;
    p_ZL13weight_memory_6_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address0;
    p_ZL13weight_memory_6_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_address1;
    p_ZL13weight_memory_6_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce0;
    p_ZL13weight_memory_6_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_ce1;
    p_ZL13weight_memory_6_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_d1;
    p_ZL13weight_memory_6_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_6_we1;
    p_ZL13weight_memory_7_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address0;
    p_ZL13weight_memory_7_address1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_address1;
    p_ZL13weight_memory_7_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce0;
    p_ZL13weight_memory_7_ce1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_ce1;
    p_ZL13weight_memory_7_d1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_d1;
    p_ZL13weight_memory_7_we1 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL13weight_memory_7_we1;
    p_ZL18eligibility_traces_0_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_address0;
    p_ZL18eligibility_traces_0_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_0_ce0;
    p_ZL18eligibility_traces_1_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_address0;
    p_ZL18eligibility_traces_1_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_1_ce0;
    p_ZL18eligibility_traces_2_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_address0;
    p_ZL18eligibility_traces_2_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_2_ce0;
    p_ZL18eligibility_traces_3_address0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_address0;
    p_ZL18eligibility_traces_3_ce0 <= grp_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER_fu_78_p_ZL18eligibility_traces_3_ce0;
    reward_factor_fu_169_p3 <= 
        tmp_s_fu_159_p4 when (tmp_fu_127_p3(0) = '1') else 
        sub_ln221_1_fu_153_p2;
        sext_ln221_1_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln221_2_fu_141_p3),10));

        sext_ln221_fu_123_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln221_1_fu_115_p3),25));

    shl_ln221_1_fu_115_p3 <= (reward_signal & ap_const_lv16_0);
    shl_ln221_2_fu_141_p3 <= (reward_signal & ap_const_lv1_0);
    sub_ln221_1_fu_153_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(sext_ln221_1_fu_149_p1));
    sub_ln221_fu_135_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(sext_ln221_fu_123_p1));
    tmp_fu_127_p3 <= reward_signal(7 downto 7);
    tmp_s_fu_159_p4 <= sub_ln221_fu_135_p2(24 downto 15);
end behav;
