-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln230 : IN STD_LOGIC_VECTOR (9 downto 0);
    sext_ln223 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_0_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_1_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_2_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL18eligibility_traces_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL18eligibility_traces_3_ce0 : OUT STD_LOGIC;
    p_ZL18eligibility_traces_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL13weight_memory_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_0_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_0_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_1_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_1_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_2_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_2_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_2_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_3_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_3_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_3_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_4_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_4_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_4_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_5_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_5_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_5_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_5_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_6_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_6_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_6_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_6_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_7_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_7_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_ZL13weight_memory_7_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_7_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of snn_top_hls_apply_reward_signal_Pipeline_REWARD_OUTER_REWARD_INNER is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv16_FF80 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln223_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sext_ln223_cast_fu_368_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln223_cast_reg_763 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln230_cast_fu_372_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln230_cast_reg_768 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln224_fu_445_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln224_reg_777 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln224_reg_777_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln224_1_fu_449_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln224_1_reg_782 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln224_2_fu_453_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln224_2_reg_787 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln224_2_reg_787_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln224_2_reg_787_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln224_2_reg_787_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln224_2_reg_787_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_793 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln_reg_793_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trace_fu_509_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal trace_reg_818 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln228_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_823 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_823_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_823_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln228_reg_823_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL13weight_memory_0_addr_reg_827 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_0_addr_reg_827_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_0_addr_reg_827_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_1_addr_reg_833 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_1_addr_reg_833_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_1_addr_reg_833_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_2_addr_reg_839 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_2_addr_reg_839_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_2_addr_reg_839_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_3_addr_reg_845 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_3_addr_reg_845_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_3_addr_reg_845_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_4_addr_reg_851 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_4_addr_reg_851_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_4_addr_reg_851_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_5_addr_reg_857 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_5_addr_reg_857_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_5_addr_reg_857_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_6_addr_reg_863 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_6_addr_reg_863_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_6_addr_reg_863_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_7_addr_reg_869 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_7_addr_reg_869_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL13weight_memory_7_addr_reg_869_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln230_fu_559_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln230_reg_875 : STD_LOGIC_VECTOR (25 downto 0);
    signal current_fu_581_p19 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_reg_880 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln230_1_fu_364_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln230_1_reg_885 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_154_cast_reg_890 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln230_fu_634_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln230_reg_897 : STD_LOGIC_VECTOR (16 downto 0);
    signal w_fu_684_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_reg_902 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln70_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln227_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln229_fu_544_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_152 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln224_fu_493_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_156 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln223_1_fu_437_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_160 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln223_1_fu_400_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (12 downto 0);
    signal p_ZL18eligibility_traces_0_ce0_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_1_ce0_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_2_ce0_local : STD_LOGIC;
    signal p_ZL18eligibility_traces_3_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_we1_local : STD_LOGIC;
    signal select_ln70_fu_726_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_2_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_2_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_2_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_3_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_3_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_3_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_4_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_4_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_4_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_5_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_5_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_5_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_6_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_6_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_6_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_7_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_7_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_7_ce1_local : STD_LOGIC;
    signal mul_ln230_1_fu_364_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln224_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln223_fu_417_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln223_fu_429_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln224_1_fu_467_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_113_fu_477_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trace_fu_509_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_538_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln230_fu_559_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal current_fu_581_p17 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln230_3_fu_638_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_114_fu_649_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln230_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln230_fu_662_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln230_fu_667_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal delta_fu_674_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln231_fu_681_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_115_fu_690_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln71_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln70_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln70_2_fu_714_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln72_fu_711_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal trace_fu_509_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trace_fu_509_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal trace_fu_509_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal trace_fu_509_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_fu_581_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_fu_581_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_mul_26s_16s_40_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component snn_top_hls_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component snn_top_hls_mul_16s_10s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component snn_top_hls_sparsemux_17_3_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_26s_16s_40_1_1_U222 : component snn_top_hls_mul_26s_16s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 26,
        din1_WIDTH => 16,
        dout_WIDTH => 40)
    port map (
        din0 => mul_ln230_reg_875,
        din1 => mul_ln230_1_fu_364_p1,
        dout => mul_ln230_1_fu_364_p2);

    sparsemux_9_2_16_1_1_U223 : component snn_top_hls_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_ZL18eligibility_traces_0_q0,
        din1 => p_ZL18eligibility_traces_1_q0,
        din2 => p_ZL18eligibility_traces_2_q0,
        din3 => p_ZL18eligibility_traces_3_q0,
        def => trace_fu_509_p9,
        sel => trunc_ln224_1_reg_782,
        dout => trace_fu_509_p11);

    mul_16s_10s_26_1_1_U224 : component snn_top_hls_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => trace_reg_818,
        din1 => mul_ln230_fu_559_p1,
        dout => mul_ln230_fu_559_p2);

    sparsemux_17_3_8_1_1_U225 : component snn_top_hls_sparsemux_17_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 8,
        CASE1 => "001",
        din1_WIDTH => 8,
        CASE2 => "010",
        din2_WIDTH => 8,
        CASE3 => "011",
        din3_WIDTH => 8,
        CASE4 => "100",
        din4_WIDTH => 8,
        CASE5 => "101",
        din5_WIDTH => 8,
        CASE6 => "110",
        din6_WIDTH => 8,
        CASE7 => "111",
        din7_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => p_ZL13weight_memory_0_q0,
        din1 => p_ZL13weight_memory_1_q0,
        din2 => p_ZL13weight_memory_2_q0,
        din3 => p_ZL13weight_memory_3_q0,
        din4 => p_ZL13weight_memory_4_q0,
        din5 => p_ZL13weight_memory_5_q0,
        din6 => p_ZL13weight_memory_6_q0,
        din7 => p_ZL13weight_memory_7_q0,
        def => current_fu_581_p17,
        sel => trunc_ln224_2_reg_787_pp0_iter3_reg,
        dout => current_fu_581_p19);

    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    i_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_156 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_156 <= select_ln223_1_fu_437_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln223_fu_394_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_160 <= add_ln223_1_fu_400_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_160 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_152 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_152 <= add_ln224_fu_493_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                lshr_ln_reg_793 <= select_ln223_fu_429_p3(5 downto 3);
                sext_ln223_cast_reg_763 <= sext_ln223_cast_fu_368_p1;
                sext_ln230_cast_reg_768 <= sext_ln230_cast_fu_372_p1;
                trunc_ln224_1_reg_782 <= trunc_ln224_1_fu_449_p1;
                trunc_ln224_2_reg_787 <= trunc_ln224_2_fu_453_p1;
                trunc_ln224_reg_777 <= trunc_ln224_fu_445_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                current_reg_880 <= current_fu_581_p19;
                icmp_ln228_reg_823 <= icmp_ln228_fu_532_p2;
                icmp_ln228_reg_823_pp0_iter3_reg <= icmp_ln228_reg_823;
                icmp_ln228_reg_823_pp0_iter4_reg <= icmp_ln228_reg_823_pp0_iter3_reg;
                icmp_ln228_reg_823_pp0_iter5_reg <= icmp_ln228_reg_823_pp0_iter4_reg;
                icmp_ln70_reg_908 <= icmp_ln70_fu_700_p2;
                lshr_ln_reg_793_pp0_iter2_reg <= lshr_ln_reg_793;
                mul_ln230_1_reg_885 <= mul_ln230_1_fu_364_p2;
                mul_ln230_reg_875 <= mul_ln230_fu_559_p2;
                p_ZL13weight_memory_0_addr_reg_827 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_0_addr_reg_827_pp0_iter4_reg <= p_ZL13weight_memory_0_addr_reg_827;
                p_ZL13weight_memory_0_addr_reg_827_pp0_iter5_reg <= p_ZL13weight_memory_0_addr_reg_827_pp0_iter4_reg;
                p_ZL13weight_memory_1_addr_reg_833 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_1_addr_reg_833_pp0_iter4_reg <= p_ZL13weight_memory_1_addr_reg_833;
                p_ZL13weight_memory_1_addr_reg_833_pp0_iter5_reg <= p_ZL13weight_memory_1_addr_reg_833_pp0_iter4_reg;
                p_ZL13weight_memory_2_addr_reg_839 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_2_addr_reg_839_pp0_iter4_reg <= p_ZL13weight_memory_2_addr_reg_839;
                p_ZL13weight_memory_2_addr_reg_839_pp0_iter5_reg <= p_ZL13weight_memory_2_addr_reg_839_pp0_iter4_reg;
                p_ZL13weight_memory_3_addr_reg_845 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_3_addr_reg_845_pp0_iter4_reg <= p_ZL13weight_memory_3_addr_reg_845;
                p_ZL13weight_memory_3_addr_reg_845_pp0_iter5_reg <= p_ZL13weight_memory_3_addr_reg_845_pp0_iter4_reg;
                p_ZL13weight_memory_4_addr_reg_851 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_4_addr_reg_851_pp0_iter4_reg <= p_ZL13weight_memory_4_addr_reg_851;
                p_ZL13weight_memory_4_addr_reg_851_pp0_iter5_reg <= p_ZL13weight_memory_4_addr_reg_851_pp0_iter4_reg;
                p_ZL13weight_memory_5_addr_reg_857 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_5_addr_reg_857_pp0_iter4_reg <= p_ZL13weight_memory_5_addr_reg_857;
                p_ZL13weight_memory_5_addr_reg_857_pp0_iter5_reg <= p_ZL13weight_memory_5_addr_reg_857_pp0_iter4_reg;
                p_ZL13weight_memory_6_addr_reg_863 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_6_addr_reg_863_pp0_iter4_reg <= p_ZL13weight_memory_6_addr_reg_863;
                p_ZL13weight_memory_6_addr_reg_863_pp0_iter5_reg <= p_ZL13weight_memory_6_addr_reg_863_pp0_iter4_reg;
                p_ZL13weight_memory_7_addr_reg_869 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
                p_ZL13weight_memory_7_addr_reg_869_pp0_iter4_reg <= p_ZL13weight_memory_7_addr_reg_869;
                p_ZL13weight_memory_7_addr_reg_869_pp0_iter5_reg <= p_ZL13weight_memory_7_addr_reg_869_pp0_iter4_reg;
                tmp_154_cast_reg_890 <= mul_ln230_1_fu_364_p2(32 downto 17);
                trace_reg_818 <= trace_fu_509_p11;
                trunc_ln224_2_reg_787_pp0_iter2_reg <= trunc_ln224_2_reg_787;
                trunc_ln224_2_reg_787_pp0_iter3_reg <= trunc_ln224_2_reg_787_pp0_iter2_reg;
                trunc_ln224_2_reg_787_pp0_iter4_reg <= trunc_ln224_2_reg_787_pp0_iter3_reg;
                trunc_ln224_2_reg_787_pp0_iter5_reg <= trunc_ln224_2_reg_787_pp0_iter4_reg;
                trunc_ln224_reg_777_pp0_iter2_reg <= trunc_ln224_reg_777;
                trunc_ln230_reg_897 <= trunc_ln230_fu_634_p1;
                w_reg_902 <= w_fu_684_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln223_1_fu_400_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv13_1));
    add_ln223_fu_417_p2 <= std_logic_vector(unsigned(i_fu_156) + unsigned(ap_const_lv7_1));
    add_ln224_fu_493_p2 <= std_logic_vector(unsigned(select_ln223_fu_429_p3) + unsigned(ap_const_lv7_1));
    add_ln230_fu_662_p2 <= std_logic_vector(unsigned(tmp_154_cast_reg_890) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln223_fu_394_p2)
    begin
        if (((icmp_ln223_fu_394_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_160)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_160;
        end if; 
    end process;

    current_fu_581_p17 <= "XXXXXXXX";
    delta_fu_674_p3 <= 
        select_ln230_fu_667_p3 when (tmp_fu_641_p3(0) = '1') else 
        tmp_154_cast_reg_890;
    icmp_ln223_fu_394_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv13_1000) else "0";
    icmp_ln224_fu_423_p2 <= "1" when (j_fu_152 = ap_const_lv7_40) else "0";
    icmp_ln228_fu_532_p2 <= "1" when (trace_fu_509_p11 = ap_const_lv16_0) else "0";
    icmp_ln230_fu_656_p2 <= "0" when (tmp_114_fu_649_p3 = ap_const_lv24_0) else "1";
    icmp_ln70_fu_700_p2 <= "1" when (signed(tmp_115_fu_690_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln71_fu_706_p2 <= "1" when (signed(w_reg_902) < signed(ap_const_lv16_FF80)) else "0";
    lshr_ln224_1_fu_467_p4 <= select_ln223_fu_429_p3(5 downto 2);
    mul_ln230_1_fu_364_p1 <= sext_ln223_cast_reg_763(16 - 1 downto 0);
    mul_ln230_fu_559_p1 <= sext_ln230_cast_reg_768(10 - 1 downto 0);
    or_ln70_fu_721_p2 <= (icmp_ln71_fu_706_p2 or icmp_ln70_reg_908);
    p_ZL13weight_memory_0_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_0_address1 <= p_ZL13weight_memory_0_addr_reg_827_pp0_iter5_reg;
    p_ZL13weight_memory_0_ce0 <= p_ZL13weight_memory_0_ce0_local;

    p_ZL13weight_memory_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_ce1 <= p_ZL13weight_memory_0_ce1_local;

    p_ZL13weight_memory_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_0_we1 <= p_ZL13weight_memory_0_we1_local;

    p_ZL13weight_memory_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_0))) then 
            p_ZL13weight_memory_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_1_address1 <= p_ZL13weight_memory_1_addr_reg_833_pp0_iter5_reg;
    p_ZL13weight_memory_1_ce0 <= p_ZL13weight_memory_1_ce0_local;

    p_ZL13weight_memory_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_ce1 <= p_ZL13weight_memory_1_ce1_local;

    p_ZL13weight_memory_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_1_we1 <= p_ZL13weight_memory_1_we1_local;

    p_ZL13weight_memory_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_1))) then 
            p_ZL13weight_memory_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_2_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_2_address1 <= p_ZL13weight_memory_2_addr_reg_839_pp0_iter5_reg;
    p_ZL13weight_memory_2_ce0 <= p_ZL13weight_memory_2_ce0_local;

    p_ZL13weight_memory_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_2_ce1 <= p_ZL13weight_memory_2_ce1_local;

    p_ZL13weight_memory_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_2_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_2_we1 <= p_ZL13weight_memory_2_we1_local;

    p_ZL13weight_memory_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_2))) then 
            p_ZL13weight_memory_2_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_3_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_3_address1 <= p_ZL13weight_memory_3_addr_reg_845_pp0_iter5_reg;
    p_ZL13weight_memory_3_ce0 <= p_ZL13weight_memory_3_ce0_local;

    p_ZL13weight_memory_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_3_ce1 <= p_ZL13weight_memory_3_ce1_local;

    p_ZL13weight_memory_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_3_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_3_we1 <= p_ZL13weight_memory_3_we1_local;

    p_ZL13weight_memory_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_3))) then 
            p_ZL13weight_memory_3_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_4_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_4_address1 <= p_ZL13weight_memory_4_addr_reg_851_pp0_iter5_reg;
    p_ZL13weight_memory_4_ce0 <= p_ZL13weight_memory_4_ce0_local;

    p_ZL13weight_memory_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_4_ce1 <= p_ZL13weight_memory_4_ce1_local;

    p_ZL13weight_memory_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_4_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_4_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_4_we1 <= p_ZL13weight_memory_4_we1_local;

    p_ZL13weight_memory_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_4))) then 
            p_ZL13weight_memory_4_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_5_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_5_address1 <= p_ZL13weight_memory_5_addr_reg_857_pp0_iter5_reg;
    p_ZL13weight_memory_5_ce0 <= p_ZL13weight_memory_5_ce0_local;

    p_ZL13weight_memory_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_5_ce1 <= p_ZL13weight_memory_5_ce1_local;

    p_ZL13weight_memory_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_5_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_5_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_5_we1 <= p_ZL13weight_memory_5_we1_local;

    p_ZL13weight_memory_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_5))) then 
            p_ZL13weight_memory_5_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_6_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_6_address1 <= p_ZL13weight_memory_6_addr_reg_863_pp0_iter5_reg;
    p_ZL13weight_memory_6_ce0 <= p_ZL13weight_memory_6_ce0_local;

    p_ZL13weight_memory_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_6_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_6_ce1 <= p_ZL13weight_memory_6_ce1_local;

    p_ZL13weight_memory_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_6_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_6_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_6_we1 <= p_ZL13weight_memory_6_we1_local;

    p_ZL13weight_memory_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_6))) then 
            p_ZL13weight_memory_6_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_7_address0 <= zext_ln229_fu_544_p1(9 - 1 downto 0);
    p_ZL13weight_memory_7_address1 <= p_ZL13weight_memory_7_addr_reg_869_pp0_iter5_reg;
    p_ZL13weight_memory_7_ce0 <= p_ZL13weight_memory_7_ce0_local;

    p_ZL13weight_memory_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            p_ZL13weight_memory_7_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_7_ce1 <= p_ZL13weight_memory_7_ce1_local;

    p_ZL13weight_memory_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            p_ZL13weight_memory_7_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_7_d1 <= select_ln70_fu_726_p3;
    p_ZL13weight_memory_7_we1 <= p_ZL13weight_memory_7_we1_local;

    p_ZL13weight_memory_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, trunc_ln224_2_reg_787_pp0_iter5_reg, icmp_ln228_reg_823_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln228_reg_823_pp0_iter5_reg = ap_const_lv1_0) and (trunc_ln224_2_reg_787_pp0_iter5_reg = ap_const_lv3_7))) then 
            p_ZL13weight_memory_7_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_0_address0 <= zext_ln227_fu_485_p1(10 - 1 downto 0);
    p_ZL18eligibility_traces_0_ce0 <= p_ZL18eligibility_traces_0_ce0_local;

    p_ZL18eligibility_traces_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_1_address0 <= zext_ln227_fu_485_p1(10 - 1 downto 0);
    p_ZL18eligibility_traces_1_ce0 <= p_ZL18eligibility_traces_1_ce0_local;

    p_ZL18eligibility_traces_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_2_address0 <= zext_ln227_fu_485_p1(10 - 1 downto 0);
    p_ZL18eligibility_traces_2_ce0 <= p_ZL18eligibility_traces_2_ce0_local;

    p_ZL18eligibility_traces_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL18eligibility_traces_3_address0 <= zext_ln227_fu_485_p1(10 - 1 downto 0);
    p_ZL18eligibility_traces_3_ce0 <= p_ZL18eligibility_traces_3_ce0_local;

    p_ZL18eligibility_traces_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL18eligibility_traces_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL18eligibility_traces_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln223_1_fu_437_p3 <= 
        add_ln223_fu_417_p2 when (icmp_ln224_fu_423_p2(0) = '1') else 
        i_fu_156;
    select_ln223_fu_429_p3 <= 
        ap_const_lv7_0 when (icmp_ln224_fu_423_p2(0) = '1') else 
        j_fu_152;
    select_ln230_fu_667_p3 <= 
        add_ln230_fu_662_p2 when (icmp_ln230_fu_656_p2(0) = '1') else 
        tmp_154_cast_reg_890;
    select_ln70_2_fu_714_p3 <= 
        ap_const_lv8_7F when (icmp_ln70_reg_908(0) = '1') else 
        ap_const_lv8_80;
    select_ln70_fu_726_p3 <= 
        select_ln70_2_fu_714_p3 when (or_ln70_fu_721_p2(0) = '1') else 
        trunc_ln72_fu_711_p1;
        sext_ln223_cast_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln223),40));

        sext_ln230_3_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln230_1_reg_885),42));

        sext_ln230_cast_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln230),26));

        sext_ln231_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_reg_880),16));

    tmp_113_fu_477_p3 <= (trunc_ln224_fu_445_p1 & lshr_ln224_1_fu_467_p4);
    tmp_114_fu_649_p3 <= (trunc_ln230_reg_897 & ap_const_lv7_0);
    tmp_115_fu_690_p4 <= w_fu_684_p2(15 downto 7);
    tmp_fu_641_p3 <= sext_ln230_3_fu_638_p1(41 downto 41);
    tmp_s_fu_538_p3 <= (trunc_ln224_reg_777_pp0_iter2_reg & lshr_ln_reg_793_pp0_iter2_reg);
    trace_fu_509_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln224_1_fu_449_p1 <= select_ln223_fu_429_p3(2 - 1 downto 0);
    trunc_ln224_2_fu_453_p1 <= select_ln223_fu_429_p3(3 - 1 downto 0);
    trunc_ln224_fu_445_p1 <= select_ln223_1_fu_437_p3(6 - 1 downto 0);
    trunc_ln230_fu_634_p1 <= mul_ln230_1_fu_364_p2(17 - 1 downto 0);
    trunc_ln72_fu_711_p1 <= w_reg_902(8 - 1 downto 0);
    w_fu_684_p2 <= std_logic_vector(unsigned(delta_fu_674_p3) + unsigned(sext_ln231_fu_681_p1));
    zext_ln227_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_113_fu_477_p3),64));
    zext_ln229_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_538_p3),64));
end behav;
