// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_decay_eligibility_traces (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        params_trace_decay_val,
        p_ZL18eligibility_traces_0_address0,
        p_ZL18eligibility_traces_0_ce0,
        p_ZL18eligibility_traces_0_q0,
        p_ZL18eligibility_traces_0_address1,
        p_ZL18eligibility_traces_0_ce1,
        p_ZL18eligibility_traces_0_we1,
        p_ZL18eligibility_traces_0_d1,
        p_ZL18eligibility_traces_1_address0,
        p_ZL18eligibility_traces_1_ce0,
        p_ZL18eligibility_traces_1_q0,
        p_ZL18eligibility_traces_1_address1,
        p_ZL18eligibility_traces_1_ce1,
        p_ZL18eligibility_traces_1_we1,
        p_ZL18eligibility_traces_1_d1,
        p_ZL18eligibility_traces_2_address0,
        p_ZL18eligibility_traces_2_ce0,
        p_ZL18eligibility_traces_2_q0,
        p_ZL18eligibility_traces_2_address1,
        p_ZL18eligibility_traces_2_ce1,
        p_ZL18eligibility_traces_2_we1,
        p_ZL18eligibility_traces_2_d1,
        p_ZL18eligibility_traces_3_address0,
        p_ZL18eligibility_traces_3_ce0,
        p_ZL18eligibility_traces_3_q0,
        p_ZL18eligibility_traces_3_address1,
        p_ZL18eligibility_traces_3_ce1,
        p_ZL18eligibility_traces_3_we1,
        p_ZL18eligibility_traces_3_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] params_trace_decay_val;
output  [9:0] p_ZL18eligibility_traces_0_address0;
output   p_ZL18eligibility_traces_0_ce0;
input  [15:0] p_ZL18eligibility_traces_0_q0;
output  [9:0] p_ZL18eligibility_traces_0_address1;
output   p_ZL18eligibility_traces_0_ce1;
output   p_ZL18eligibility_traces_0_we1;
output  [15:0] p_ZL18eligibility_traces_0_d1;
output  [9:0] p_ZL18eligibility_traces_1_address0;
output   p_ZL18eligibility_traces_1_ce0;
input  [15:0] p_ZL18eligibility_traces_1_q0;
output  [9:0] p_ZL18eligibility_traces_1_address1;
output   p_ZL18eligibility_traces_1_ce1;
output   p_ZL18eligibility_traces_1_we1;
output  [15:0] p_ZL18eligibility_traces_1_d1;
output  [9:0] p_ZL18eligibility_traces_2_address0;
output   p_ZL18eligibility_traces_2_ce0;
input  [15:0] p_ZL18eligibility_traces_2_q0;
output  [9:0] p_ZL18eligibility_traces_2_address1;
output   p_ZL18eligibility_traces_2_ce1;
output   p_ZL18eligibility_traces_2_we1;
output  [15:0] p_ZL18eligibility_traces_2_d1;
output  [9:0] p_ZL18eligibility_traces_3_address0;
output   p_ZL18eligibility_traces_3_ce0;
input  [15:0] p_ZL18eligibility_traces_3_q0;
output  [9:0] p_ZL18eligibility_traces_3_address1;
output   p_ZL18eligibility_traces_3_ce1;
output   p_ZL18eligibility_traces_3_we1;
output  [15:0] p_ZL18eligibility_traces_3_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln202_reg_384;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [31:0] sext_ln205_fu_172_p1;
reg  signed [31:0] sext_ln205_reg_379;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln202_fu_194_p2;
wire   [1:0] trunc_ln203_1_fu_249_p1;
reg   [1:0] trunc_ln203_1_reg_388;
wire    ap_block_pp0_stage1_11001;
reg   [1:0] trunc_ln203_1_reg_388_pp0_iter1_reg;
reg   [9:0] p_ZL18eligibility_traces_0_addr_reg_395;
reg   [9:0] p_ZL18eligibility_traces_0_addr_reg_395_pp0_iter1_reg;
reg   [9:0] p_ZL18eligibility_traces_1_addr_reg_401;
reg   [9:0] p_ZL18eligibility_traces_1_addr_reg_401_pp0_iter1_reg;
reg   [9:0] p_ZL18eligibility_traces_2_addr_reg_407;
reg   [9:0] p_ZL18eligibility_traces_2_addr_reg_407_pp0_iter1_reg;
reg   [9:0] p_ZL18eligibility_traces_3_addr_reg_413;
reg   [9:0] p_ZL18eligibility_traces_3_addr_reg_413_pp0_iter1_reg;
wire   [15:0] tmp_fu_295_p11;
reg  signed [15:0] tmp_reg_419;
wire   [31:0] mul_ln205_fu_321_p2;
reg   [31:0] mul_ln205_reg_424;
reg   [15:0] trunc_ln_reg_433;
wire   [63:0] zext_ln205_fu_271_p1;
wire    ap_block_pp0_stage1;
reg   [6:0] j_fu_82;
wire   [6:0] add_ln203_fu_279_p2;
wire    ap_loop_init;
reg   [6:0] i_fu_86;
wire   [6:0] select_ln202_1_fu_237_p3;
reg   [12:0] indvar_flatten_fu_90;
wire   [12:0] add_ln202_1_fu_200_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    p_ZL18eligibility_traces_0_ce0_local;
reg    p_ZL18eligibility_traces_0_we1_local;
wire   [0:0] icmp_ln205_fu_326_p2;
reg   [15:0] p_ZL18eligibility_traces_0_d1_local;
reg    p_ZL18eligibility_traces_0_ce1_local;
reg    p_ZL18eligibility_traces_1_ce0_local;
reg    p_ZL18eligibility_traces_1_we1_local;
reg   [15:0] p_ZL18eligibility_traces_1_d1_local;
reg    p_ZL18eligibility_traces_1_ce1_local;
reg    p_ZL18eligibility_traces_2_ce0_local;
reg    p_ZL18eligibility_traces_2_we1_local;
reg   [15:0] p_ZL18eligibility_traces_2_d1_local;
reg    p_ZL18eligibility_traces_2_ce1_local;
reg    p_ZL18eligibility_traces_3_ce0_local;
reg    p_ZL18eligibility_traces_3_we1_local;
reg   [15:0] p_ZL18eligibility_traces_3_d1_local;
reg    p_ZL18eligibility_traces_3_ce1_local;
wire   [0:0] icmp_ln203_fu_223_p2;
wire   [6:0] add_ln202_fu_217_p2;
wire   [6:0] select_ln202_fu_229_p3;
wire   [5:0] trunc_ln203_fu_245_p1;
wire   [3:0] lshr_ln_fu_253_p4;
wire   [9:0] tmp_s_fu_263_p3;
wire   [15:0] tmp_fu_295_p9;
wire  signed [15:0] mul_ln205_fu_321_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_295_p1;
wire   [1:0] tmp_fu_295_p3;
wire  signed [1:0] tmp_fu_295_p5;
wire  signed [1:0] tmp_fu_295_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j_fu_82 = 7'd0;
#0 i_fu_86 = 7'd0;
#0 indvar_flatten_fu_90 = 13'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U255(
    .din0(p_ZL18eligibility_traces_0_q0),
    .din1(p_ZL18eligibility_traces_1_q0),
    .din2(p_ZL18eligibility_traces_2_q0),
    .din3(p_ZL18eligibility_traces_3_q0),
    .def(tmp_fu_295_p9),
    .sel(trunc_ln203_1_reg_388),
    .dout(tmp_fu_295_p11)
);

snn_top_hls_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U256(
    .din0(tmp_reg_419),
    .din1(mul_ln205_fu_321_p1),
    .dout(mul_ln205_fu_321_p2)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_86 <= 7'd0;
    end else if (((icmp_ln202_reg_384 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_86 <= select_ln202_1_fu_237_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln202_fu_194_p2 == 1'd0))) begin
            indvar_flatten_fu_90 <= add_ln202_1_fu_200_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_90 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        j_fu_82 <= 7'd0;
    end else if (((icmp_ln202_reg_384 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        j_fu_82 <= add_ln203_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        mul_ln205_reg_424 <= mul_ln205_fu_321_p2;
        p_ZL18eligibility_traces_0_addr_reg_395 <= zext_ln205_fu_271_p1;
        p_ZL18eligibility_traces_0_addr_reg_395_pp0_iter1_reg <= p_ZL18eligibility_traces_0_addr_reg_395;
        p_ZL18eligibility_traces_1_addr_reg_401 <= zext_ln205_fu_271_p1;
        p_ZL18eligibility_traces_1_addr_reg_401_pp0_iter1_reg <= p_ZL18eligibility_traces_1_addr_reg_401;
        p_ZL18eligibility_traces_2_addr_reg_407 <= zext_ln205_fu_271_p1;
        p_ZL18eligibility_traces_2_addr_reg_407_pp0_iter1_reg <= p_ZL18eligibility_traces_2_addr_reg_407;
        p_ZL18eligibility_traces_3_addr_reg_413 <= zext_ln205_fu_271_p1;
        p_ZL18eligibility_traces_3_addr_reg_413_pp0_iter1_reg <= p_ZL18eligibility_traces_3_addr_reg_413;
        trunc_ln203_1_reg_388 <= trunc_ln203_1_fu_249_p1;
        trunc_ln203_1_reg_388_pp0_iter1_reg <= trunc_ln203_1_reg_388;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln202_reg_384 <= icmp_ln202_fu_194_p2;
        sext_ln205_reg_379 <= sext_ln205_fu_172_p1;
        tmp_reg_419 <= tmp_fu_295_p11;
        trunc_ln_reg_433 <= {{mul_ln205_reg_424[23:8]}};
    end
end

always @ (*) begin
    if (((icmp_ln202_reg_384 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL18eligibility_traces_0_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL18eligibility_traces_0_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_0_d1_local = trunc_ln_reg_433;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_0_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_0_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_0_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_326_p2 == 1'd1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd0)))) begin
        p_ZL18eligibility_traces_0_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL18eligibility_traces_1_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL18eligibility_traces_1_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_1_d1_local = trunc_ln_reg_433;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_1_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_1_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_1_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_326_p2 == 1'd1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd1)))) begin
        p_ZL18eligibility_traces_1_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL18eligibility_traces_2_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL18eligibility_traces_2_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_2_d1_local = trunc_ln_reg_433;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_2_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_2_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_2_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_326_p2 == 1'd1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd2)))) begin
        p_ZL18eligibility_traces_2_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL18eligibility_traces_3_ce0_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL18eligibility_traces_3_ce1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_ZL18eligibility_traces_3_d1_local = trunc_ln_reg_433;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_ZL18eligibility_traces_3_d1_local = 16'd0;
        end else begin
            p_ZL18eligibility_traces_3_d1_local = 'bx;
        end
    end else begin
        p_ZL18eligibility_traces_3_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_326_p2 == 1'd1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln203_1_reg_388_pp0_iter1_reg == 2'd3)))) begin
        p_ZL18eligibility_traces_3_we1_local = 1'b1;
    end else begin
        p_ZL18eligibility_traces_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln202_1_fu_200_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln202_fu_217_p2 = (i_fu_86 + 7'd1);

assign add_ln203_fu_279_p2 = (select_ln202_fu_229_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign icmp_ln202_fu_194_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln203_fu_223_p2 = ((j_fu_82 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_326_p2 = ((mul_ln205_reg_424 == 32'd0) ? 1'b1 : 1'b0);

assign lshr_ln_fu_253_p4 = {{select_ln202_fu_229_p3[5:2]}};

assign mul_ln205_fu_321_p1 = sext_ln205_reg_379;

assign p_ZL18eligibility_traces_0_address0 = zext_ln205_fu_271_p1;

assign p_ZL18eligibility_traces_0_address1 = p_ZL18eligibility_traces_0_addr_reg_395_pp0_iter1_reg;

assign p_ZL18eligibility_traces_0_ce0 = p_ZL18eligibility_traces_0_ce0_local;

assign p_ZL18eligibility_traces_0_ce1 = p_ZL18eligibility_traces_0_ce1_local;

assign p_ZL18eligibility_traces_0_d1 = p_ZL18eligibility_traces_0_d1_local;

assign p_ZL18eligibility_traces_0_we1 = p_ZL18eligibility_traces_0_we1_local;

assign p_ZL18eligibility_traces_1_address0 = zext_ln205_fu_271_p1;

assign p_ZL18eligibility_traces_1_address1 = p_ZL18eligibility_traces_1_addr_reg_401_pp0_iter1_reg;

assign p_ZL18eligibility_traces_1_ce0 = p_ZL18eligibility_traces_1_ce0_local;

assign p_ZL18eligibility_traces_1_ce1 = p_ZL18eligibility_traces_1_ce1_local;

assign p_ZL18eligibility_traces_1_d1 = p_ZL18eligibility_traces_1_d1_local;

assign p_ZL18eligibility_traces_1_we1 = p_ZL18eligibility_traces_1_we1_local;

assign p_ZL18eligibility_traces_2_address0 = zext_ln205_fu_271_p1;

assign p_ZL18eligibility_traces_2_address1 = p_ZL18eligibility_traces_2_addr_reg_407_pp0_iter1_reg;

assign p_ZL18eligibility_traces_2_ce0 = p_ZL18eligibility_traces_2_ce0_local;

assign p_ZL18eligibility_traces_2_ce1 = p_ZL18eligibility_traces_2_ce1_local;

assign p_ZL18eligibility_traces_2_d1 = p_ZL18eligibility_traces_2_d1_local;

assign p_ZL18eligibility_traces_2_we1 = p_ZL18eligibility_traces_2_we1_local;

assign p_ZL18eligibility_traces_3_address0 = zext_ln205_fu_271_p1;

assign p_ZL18eligibility_traces_3_address1 = p_ZL18eligibility_traces_3_addr_reg_413_pp0_iter1_reg;

assign p_ZL18eligibility_traces_3_ce0 = p_ZL18eligibility_traces_3_ce0_local;

assign p_ZL18eligibility_traces_3_ce1 = p_ZL18eligibility_traces_3_ce1_local;

assign p_ZL18eligibility_traces_3_d1 = p_ZL18eligibility_traces_3_d1_local;

assign p_ZL18eligibility_traces_3_we1 = p_ZL18eligibility_traces_3_we1_local;

assign select_ln202_1_fu_237_p3 = ((icmp_ln203_fu_223_p2[0:0] == 1'b1) ? add_ln202_fu_217_p2 : i_fu_86);

assign select_ln202_fu_229_p3 = ((icmp_ln203_fu_223_p2[0:0] == 1'b1) ? 7'd0 : j_fu_82);

assign sext_ln205_fu_172_p1 = $signed(params_trace_decay_val);

assign tmp_fu_295_p9 = 'bx;

assign tmp_s_fu_263_p3 = {{trunc_ln203_fu_245_p1}, {lshr_ln_fu_253_p4}};

assign trunc_ln203_1_fu_249_p1 = select_ln202_fu_229_p3[1:0];

assign trunc_ln203_fu_245_p1 = select_ln202_1_fu_237_p3[5:0];

assign zext_ln205_fu_271_p1 = tmp_s_fu_263_p3;

endmodule //snn_top_hls_decay_eligibility_traces
